# SPDX-License-Identifier: Apache-2.0
# k9x_studio scaffold generator service

import io
import re
import zipfile
from datetime import datetime
from pathlib import Path

from jinja2 import ChoiceLoader, Environment, FileSystemLoader

# Reuse canonical generator templates when variable signatures match.
# Studio-only templates (validation_loop, critic_actor) live in STUDIO_TEMPLATES_DIR.
import os as _os
_env_tpl = _os.environ.get("K9X_GENERATOR_TEMPLATES_DIR")
GENERATOR_TEMPLATES_DIR = (
    Path(_env_tpl) if _env_tpl
    else Path(__file__).resolve().parents[4] / "k9-aif-framework" / "generator" / "templates"
)
STUDIO_TEMPLATES_DIR = Path(__file__).parent.parent / "templates"

_loader = ChoiceLoader([
    FileSystemLoader(str(GENERATOR_TEMPLATES_DIR)),
    FileSystemLoader(str(STUDIO_TEMPLATES_DIR)),
])
_env = Environment(loader=_loader)


def to_snake(name: str) -> str:
    s = re.sub(r"[\s\-]+", "_", name.strip())   # spaces/hyphens → underscore first
    s = re.sub(r"(.)([A-Z][a-z]+)", r"\1_\2", s)
    s = re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", s)
    s = re.sub(r"_+", "_", s).lower().strip("_")  # collapse duplicates, normalise
    return s


def to_pascal(name: str) -> str:
    return "".join(p.capitalize() for p in to_snake(name).split("_"))


_env.filters["to_snake"] = to_snake
_env.filters["to_pascal"] = to_pascal


def _render(template_name: str, ctx: dict) -> str:
    return _env.get_template(template_name).render(ctx)


# generator template names used for compatible types; studio templates for the rest
AGENT_TEMPLATE_MAP = {
    "BaseAgent": "agent_template.py.j2",          # reused from generator
    "K9ValidationLoopAgent": "agent_validation_loop.py.j2",   # studio-only
    "K9CriticActorAgent": "agent_critic_actor.py.j2",         # studio-only
}


def generate_scaffold(project: dict) -> io.BytesIO:
    """
    Generate a K9-AIF scaffold ZIP from the studio project definition.

    project dict keys:
      project_name, author, domain, description,
      orchestrators: [{name, squad}],
      squads:        [{name, agents: [str]}],
      agents:        [{name, type, model, pattern, description}]
    """
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    app_name = to_pascal(project["project_name"])
    app_folder = to_snake(project["project_name"])
    author = project.get("author", "")
    domain = project.get("domain", "")

    agents_by_name = {a["name"]: a for a in project.get("agents", [])}
    squads = project.get("squads", [])
    orchestrators = project.get("orchestrators", [])

    zip_buf = io.BytesIO()

    with zipfile.ZipFile(zip_buf, mode="w", compression=zipfile.ZIP_DEFLATED) as zf:

        def add(path: str, content: str):
            info = zipfile.ZipInfo(path)
            info.compress_type = zipfile.ZIP_DEFLATED
            # Set executable bit for shell scripts
            if path.endswith(".sh"):
                info.external_attr = 0o755 << 16
            else:
                info.external_attr = 0o644 << 16
            zf.writestr(info, content)

        # ── agents ────────────────────────────────────────────────────
        for agent_def in project.get("agents", []):
            agent_name = agent_def["name"]
            agent_type = agent_def.get("type", "BaseAgent")
            snake = to_snake(agent_name)

            template_name = AGENT_TEMPLATE_MAP.get(agent_type, "agent_base.py.j2")
            py_code = _render(template_name, {
                "class_name": agent_name,
                "app_name": app_name,
                "timestamp": timestamp,
            })
            add(f"{app_folder}/agents/src/{snake}.py", py_code)

            yaml_code = _render("agent.yaml.j2", {
                "agent": agent_def,
                "domain": domain,
                "timestamp": timestamp,
            })
            add(f"{app_folder}/agents/yaml/{snake}.yaml", yaml_code)

        # ── __init__.py stubs ─────────────────────────────────────────
        for subdir in ("", "agents/src", "agents/yaml", "orchestrators", "config", "utils", "tests", "squads/src", "squads/yaml"):
            init_path = f"{app_folder}/{subdir}/__init__.py" if subdir else f"{app_folder}/__init__.py"
            add(init_path, f"# {app_name} — generated by k9x_studio\n")

        # ── test stub ─────────────────────────────────────────────────
        test_stub = f'''# SPDX-License-Identifier: Apache-2.0
# Generated by k9x_studio on {timestamp}

import pytest
from unittest.mock import patch, MagicMock


@pytest.fixture
def sample_payload():
    return {{"event_type": "{to_snake(app_name)}_event", "data": {{}}}}


# TODO: Add agent tests here
# Example:
# from {app_folder.replace("/", ".")}.agents.src.my_agent import MyAgent
# def test_my_agent(sample_payload):
#     agent = MyAgent(config={{}})
#     result = agent.execute(sample_payload)
#     assert "output" in result
'''
        add(f"{app_folder}/tests/test_{to_snake(app_name)}.py", test_stub)
        add(f"{app_folder}/tests/conftest.py", f'# pytest conftest for {app_name}\nimport pytest\n')

        # ── squads ────────────────────────────────────────────────────
        # One YAML per squad in squads/yaml/
        for squad in squads:
            squad_yaml = f"# SPDX-License-Identifier: Apache-2.0\n# Generated by k9x_studio on {timestamp}\n\nsquads:\n"
            squad_yaml += f"  {squad['name']}:\n"
            squad_yaml += f"    description: \"{squad['name']} agent pipeline — {domain}\"\n"
            squad_yaml += "    agents:\n"
            for a in squad["agents"]:
                squad_yaml += f"      - {a}\n"
            squad_yaml += "    flow:\n"
            for a in squad["agents"]:
                squad_yaml += f"      - agent: {a}\n"
                squad_yaml += f"        result_key: {to_snake(a)}\n"
            add(f"{app_folder}/squads/yaml/{to_snake(squad['name'])}.yaml", squad_yaml)

            # Squad src stub — extend BaseSquad only if custom behaviour needed
            squad_src = f'''# SPDX-License-Identifier: Apache-2.0
# Generated by k9x_studio on {timestamp}
# Extend BaseSquad only if you need custom squad behaviour.
# Default: SquadLoader wires agents from YAML — no code changes required.

from k9_aif_abb.k9_squad.base_squad import BaseSquad


class {squad['name']}(BaseSquad):
    """Squad: {squad['name']} — {domain}"""
    pass
'''
            add(f"{app_folder}/squads/src/{to_snake(squad['name'])}.py", squad_src)

        # Also write combined squads.yaml to config/ for backward compatibility
        all_squads_yaml = f"# SPDX-License-Identifier: Apache-2.0\n# Generated by k9x_studio on {timestamp}\n\nsquads:\n"
        for squad in squads:
            all_squads_yaml += f"  {squad['name']}:\n"
            all_squads_yaml += f"    description: \"{squad['name']} agent pipeline — {domain}\"\n"
            all_squads_yaml += "    agents:\n"
            for a in squad["agents"]:
                all_squads_yaml += f"      - {a}\n"
            all_squads_yaml += "    flow:\n"
            for a in squad["agents"]:
                all_squads_yaml += f"      - agent: {a}\n"
                all_squads_yaml += f"        result_key: {to_snake(a)}\n"
            all_squads_yaml += "\n"
        add(f"{app_folder}/config/squads.yaml", all_squads_yaml)

        # ── orchestrators ─────────────────────────────────────────────
        for orch_def in orchestrators:
            orch_name = orch_def["name"]
            squad_name = orch_def.get("squad", squads[0]["name"] if squads else "DefaultSquad")

            # collect agents for this squad
            squad_agents = []
            for sq in squads:
                if sq["name"] == squad_name:
                    squad_agents = sq["agents"]
                    break

            orch_code = _render("orchestrator.py.j2", {
                "app_name": app_name,
                "app_folder": app_folder,
                "orchestrator_name": orch_name,
                "squad_name": squad_name,
                "agent_names": squad_agents,
                "timestamp": timestamp,
            })
            add(f"{app_folder}/orchestrators/{to_snake(orch_name)}.py", orch_code)

        # ── config.yaml — reuse canonical generator template ─────────
        import os as _os2
        ollama_base_url = (
            project.get("ollama_base_url", "").strip()
            or _os2.environ.get("OLLAMA_BASE_URL", "http://localhost:11434")
        )
        config_yaml = _render("config.yaml.j2", {
            "app_name": app_name,
            "app_folder": app_folder,
            "author": author,
            "domain": domain,
            "timestamp": timestamp,
            "ollama_base_url": ollama_base_url,
        })
        add(f"{app_folder}/config/config.yaml", config_yaml)

        # ── main.py ───────────────────────────────────────────────────
        main_py = _render("main.py.j2", {
            "app_name": app_name,
            "app_folder": app_folder,
            "domain": domain,
            "orchestrators": orchestrators,
            "timestamp": timestamp,
        })
        add(f"{app_folder}/main.py", main_py)

        # ── utils/agent_loader.py ─────────────────────────────────────
        agent_loader_py = f'''# SPDX-License-Identifier: Apache-2.0
# Generated by k9x_studio on {timestamp}

import yaml
from pathlib import Path
from typing import Any, Dict


class AgentLoader:
    """Merges per-agent YAML with the global config dict."""

    def __init__(self, agents_yaml_dir: Path):
        self._dir = Path(agents_yaml_dir)
        self._cache: Dict[str, dict] = {{}}

    def _load(self, agent_name: str) -> dict:
        if agent_name not in self._cache:
            snake = "_".join(
                p.lower() for p in __import__("re").sub(
                    r"([a-z0-9])([A-Z])", r"\\1_\\2",
                    __import__("re").sub(r"(.)([A-Z][a-z]+)", r"\\1_\\2", agent_name)
                ).split("_")
            )
            path = self._dir / f"{{snake}}.yaml"
            if path.exists():
                with open(path) as f:
                    self._cache[agent_name] = yaml.safe_load(f) or {{}}
            else:
                self._cache[agent_name] = {{}}
        return self._cache[agent_name]

    def merge_with_global(self, agent_name: str, global_config: dict) -> dict:
        merged = dict(global_config)
        merged.update(self._load(agent_name))
        return merged
'''
        add(f"{app_folder}/utils/agent_loader.py", agent_loader_py)

        # ── .env ─────────────────────────────────────────────────────
        framework_path = project.get("framework_path", "").strip()
        platforms = project.get("platforms", [])

        env_lines = [
            f"# {app_name} — environment configuration",
            f"# Generated by k9x_studio on {timestamp}",
            "",
            "# K9-AIF Framework",
        ]
        if framework_path:
            # Ensure absolute path — strip accidental leading tilde for clarity
            fp = framework_path.lstrip()
            if not fp.startswith('/') and not fp.startswith('~'):
                fp = '/' + fp
            env_lines += [
                f'K9_FRAMEWORK_PATH="{fp}"',
            ]
        else:
            env_lines += [
                '# K9_FRAMEWORK_PATH="/path/to/k9-aif-framework"  # set this',
            ]
        env_lines += [
            "",
            "# LLM — Ollama (default)",
            'OLLAMA_BASE_URL="http://localhost:11434"',
            "",
            "# LLM — OpenAI (uncomment if using OpenAI backend in config.yaml)",
            '# OPENAI_API_KEY="sk-..."',
            "",
            "# LLM — Grok / xAI (uncomment if using Grok backend in config.yaml)",
            '# GROK_API_KEY="xai-..."',
            "",
            "# App",
            f'APP_NAME="{app_name}"',
            f'APP_DOMAIN="{domain}"',
        ]
        add(f"{app_folder}/.env", "\n".join(env_lines) + "\n")

        # ── .env.example ──────────────────────────────────────────────
        env_example_lines = [
            f"# {app_name} — environment variable reference",
            f"# Copy to .env and fill in values. Never commit .env to source control.",
            f"# Generated by k9x_studio on {timestamp}",
            "",
            "# ── K9-AIF Framework path ────────────────────────────────",
            "# Absolute path to your k9-aif-framework clone.",
            "# Do not use ~ — use the full path.",
            'K9_FRAMEWORK_PATH=',
            "",
            "# ── LLM — Ollama (default, local, no key needed) ─────────",
            'OLLAMA_BASE_URL=http://localhost:11434',
            "",
            "# ── LLM — OpenAI ─────────────────────────────────────────",
            "# Set backend: openai and api_key_env: OPENAI_API_KEY in config.yaml",
            'OPENAI_API_KEY=',
            "",
            "# ── LLM — Grok / xAI ─────────────────────────────────────",
            "# Set backend: openai-compatible and api_key_env: GROK_API_KEY in config.yaml",
            'GROK_API_KEY=',
            "",
            "# ── App ──────────────────────────────────────────────────",
            f'APP_NAME={app_name}',
            f'APP_DOMAIN={domain}',
        ]
        add(f"{app_folder}/.env.example", "\n".join(env_example_lines) + "\n")

        # ── run.sh ────────────────────────────────────────────────────
        run_sh = f"""#!/usr/bin/env bash
# {app_name} — run script generated by k9x_studio
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${{BASH_SOURCE[0]}}")" && pwd)"
source "$SCRIPT_DIR/.env"

if [ -z "${{K9_FRAMEWORK_PATH:-}}" ]; then
  echo "ERROR: K9_FRAMEWORK_PATH not set. Edit .env and set it to your k9-aif-framework folder."
  exit 1
fi

# Expand ~ in case .env uses ~/path notation
K9_FRAMEWORK_PATH="${{K9_FRAMEWORK_PATH/#\~/$HOME}}"

export PYTHONPATH="$K9_FRAMEWORK_PATH:${{PYTHONPATH:-}}"
# Development mode — skips governance pipeline for local testing
export K9_ENV="${{K9_ENV:-development}}"
echo "Using framework: $K9_FRAMEWORK_PATH (K9_ENV=$K9_ENV)"
python "$SCRIPT_DIR/main.py" "$@"
"""
        add(f"{app_folder}/run.sh", run_sh)

        # ── CLAUDE.md — just imports the framework's CLAUDE.md ───────
        fw_ref = framework_path if framework_path else "/path/to/k9-aif-framework"
        claude_md = f"@{fw_ref}/CLAUDE.md\n"
        add(f"{app_folder}/CLAUDE.md", claude_md)

        # ── README ────────────────────────────────────────────────────
        llm_provider = project.get('llm_provider', '')
        llm_model    = project.get('llm_model', '')
        gen_source   = project.get('generation_source', '')
        scoring      = project.get('generation_scoring') or {}
        llm_line     = f"{llm_provider} · {llm_model}" if llm_model else "—"
        source_line  = gen_source if gen_source else "rule-based"
        score_line   = ""
        if scoring:
            winner = scoring.get('winner', '')
            ws     = scoring.get(winner, {})
            ls     = scoring.get('llm' if winner == 'rule_based' else 'rule_based', {})
            score_line = f" (winner score: {ws.get('score','?')} vs {ls.get('score','?')})"

        readme = f"""# {app_name}

| | |
|---|---|
| **Studio** | [studio.k9x.ai](https://studio.k9x.ai) |
| **Framework** | [k9x.ai](https://k9x.ai) — K9-AIF Architecture-First |
| **Generated** | {timestamp} |
| **Author** | {author or '—'} |
| **LLM** | {llm_line} |
| **Generation** | {source_line}{score_line} |

---

**Domain:** {domain}
**Description:** {project.get('description', '')}

## Quick start

```bash
# 1. Confirm .env has the correct K9_FRAMEWORK_PATH
cat .env

# 2. Run
bash run.sh
```

## Prerequisites

- k9-aif-framework cloned at `{fw_ref}`
- Ollama running at http://localhost:11434
- Python 3.10+

## Structure

```
{app_folder}/
├── agents/src/       # Agent Python classes
├── agents/yaml/      # Agent configuration
├── orchestrators/    # Orchestrator classes
├── config/           # config.yaml + squads.yaml
├── utils/            # agent_loader.py
├── main.py           # Entry point
├── run.sh            # Launch script
├── .env              # Set K9_FRAMEWORK_PATH here
└── CLAUDE.md         # Claude Code context
```
"""
        add(f"{app_folder}/README.md", readme)

    zip_buf.seek(0)
    return zip_buf
