# SPDX-License-Identifier: Apache-2.0
# k9x_studio scaffold generator service

import io
import json
import re
import zipfile
import zlib
from datetime import datetime
from pathlib import Path
from typing import Optional

import requests
from jinja2 import ChoiceLoader, Environment, FileSystemLoader

# Reuse canonical generator templates when variable signatures match.
# Studio-only templates (validation_loop, critic_actor) live in STUDIO_TEMPLATES_DIR.
import os as _os
_env_tpl = _os.environ.get("K9X_GENERATOR_TEMPLATES_DIR")
GENERATOR_TEMPLATES_DIR = (
    Path(_env_tpl) if _env_tpl
    else Path(__file__).resolve().parents[4] / "k9-aif-framework" / "generator" / "templates"
)
STUDIO_TEMPLATES_DIR = Path(__file__).parent.parent / "templates"

_loader = ChoiceLoader([
    FileSystemLoader(str(GENERATOR_TEMPLATES_DIR)),
    FileSystemLoader(str(STUDIO_TEMPLATES_DIR)),
])
_env = Environment(loader=_loader)


def to_snake(name: str) -> str:
    s = re.sub(r"[\s\-]+", "_", name.strip())   # spaces/hyphens → underscore first
    s = re.sub(r"(.)([A-Z][a-z]+)", r"\1_\2", s)
    s = re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", s)
    s = re.sub(r"_+", "_", s).lower().strip("_")  # collapse duplicates, normalise
    return s


def to_pascal(name: str) -> str:
    return "".join(p.capitalize() for p in to_snake(name).split("_"))


_env.filters["to_snake"] = to_snake
_env.filters["to_pascal"] = to_pascal


def _render(template_name: str, ctx: dict) -> str:
    return _env.get_template(template_name).render(ctx)


# generator template names used for compatible types; studio templates for the rest
AGENT_TEMPLATE_MAP = {
    "BaseAgent": "agent_template.py.j2",          # reused from generator
    "K9ValidationLoopAgent": "agent_validation_loop.py.j2",   # studio-only
    "K9CriticActorAgent": "agent_critic_actor.py.j2",         # studio-only
}

# Agent types with a verified K9-AIF ABB/OOB base class. Anything else falls
# back to BaseAgent (matches AGENT_TEMPLATE_MAP.get(..., "agent_base.py.j2")).
_KNOWN_AGENT_BASE_TYPES = ("BaseAgent", "K9ValidationLoopAgent", "K9CriticActorAgent")

PLANTUML_SERVER = _os.environ.get("PLANTUML_SERVER_URL", "https://www.plantuml.com/plantuml")

# k9-aif-framework clone target for setup.sh's "clone framework" option
FRAMEWORK_REPO_URL = _os.environ.get(
    "K9_FRAMEWORK_REPO_URL", "https://github.com/k9aif/k9-aif-framework.git"
)


def generate_class_diagram_puml(project: dict, app_name: str, app_folder: str, timestamp: str) -> str:
    """
    Build a high-level PlantUML class diagram for this project: the agents,
    squads and orchestrators the user designed, plus the K9-AIF ABB/OOB base
    classes they extend. Follows the conventions in puml/README.md
    (abstract vs concrete marking, package-per-squad grouping, `--|>` for
    inheritance, `..>` for "loads" dependencies).
    """
    agents = project.get("agents", [])
    squads = project.get("squads", [])
    orchestrators = project.get("orchestrators", [])

    def agent_base(agent_def: dict) -> str:
        t = agent_def.get("type", "BaseAgent")
        return t if t in _KNOWN_AGENT_BASE_TYPES else "BaseAgent"

    used_types = {agent_base(a) for a in agents}
    has_validation = "K9ValidationLoopAgent" in used_types
    has_critic = "K9CriticActorAgent" in used_types

    lines: list = []
    lines.append(f"@startuml {app_folder}_class_diagram")
    lines.append("")
    lines.append("' Generated by k9x Studio. k9x.ai")
    lines.append("")
    lines.append("skinparam classBackgroundColor #FAFAFA")
    lines.append("skinparam classBorderColor #AAAAAA")
    lines.append("skinparam ArrowColor #555555")
    lines.append("skinparam PackageBorderColor #CCCCCC")
    lines.append("skinparam PackageBackgroundColor #F5F7FF")
    lines.append("skinparam defaultFontSize 12")
    lines.append("hide circle")
    lines.append("")
    lines.append(f"title {app_name} - Class Diagram")
    lines.append("")

    # ── K9-AIF framework base classes (ABB / OOB) ───────────────────────
    lines.append('package "K9-AIF Framework (ABB / OOB)" #E8F5E9 {')
    lines.append("  abstract class BaseAgent {")
    lines.append("    + {abstract} execute(payload: dict) : dict")
    lines.append("  }")

    if has_validation:
        lines.append("  abstract class BaseValidationLoopAgent {")
        lines.append("    + execute(payload: dict) : dict")
        lines.append("    + {abstract} generate_hypothesis(loop_ctx)")
        lines.append("    + {abstract} run_validation(hypothesis, loop_ctx)")
        lines.append("    + {abstract} evaluate_observation(result, loop_ctx)")
        lines.append("    + {abstract} should_continue(obs, loop_ctx) : ValidationDisposition")
        lines.append("    + {abstract} finalize(loop_ctx) : ValidationLoopResult")
        lines.append("  }")
        lines.append("  class K9ValidationLoopAgent")
        lines.append("  BaseAgent <|-- BaseValidationLoopAgent")
        lines.append("  BaseValidationLoopAgent <|-- K9ValidationLoopAgent")

    if has_critic:
        lines.append("  abstract class BaseCriticActorAgent {")
        lines.append("    + execute(payload: dict) : dict")
        lines.append("    + {abstract} generate(ctx)")
        lines.append("    + {abstract} critique(draft, ctx) : dict")
        lines.append("    + {abstract} refine(draft, feedback, ctx)")
        lines.append("    + {abstract} should_accept(critique, ctx) : bool")
        lines.append("    + {abstract} finalize(ctx) : CriticActorResult")
        lines.append("  }")
        lines.append("  class K9CriticActorAgent")
        lines.append("  BaseAgent <|-- BaseCriticActorAgent")
        lines.append("  BaseCriticActorAgent <|-- K9CriticActorAgent")

    if squads:
        lines.append("  class BaseSquad {")
        lines.append("    + execute(payload: dict) : dict")
        lines.append("  }")

    if orchestrators:
        lines.append("  abstract class BaseOrchestrator {")
        lines.append("    + {abstract} execute_flow(payload: dict) : dict")
        lines.append("  }")

    lines.append("}")
    lines.append("")

    # ── agents, grouped by squad ─────────────────────────────────────────
    if agents:
        squad_agent_names = {a for sq in squads for a in sq.get("agents", [])}
        unassigned = [a for a in agents if a["name"] not in squad_agent_names]

        lines.append(f'package "{app_name} Agents" {{')
        for sq in squads:
            lines.append(f'  package "{sq["name"]}" {{')
            for agent_name in sq.get("agents", []):
                lines.append(f"    class {agent_name}")
            lines.append(f"    class {sq['name']}")
            lines.append("  }")
        if unassigned:
            if squads:
                lines.append('  package "Unassigned" {')
                for a in unassigned:
                    lines.append(f"    class {a['name']}")
                lines.append("  }")
            else:
                for a in unassigned:
                    lines.append(f"  class {a['name']}")
        lines.append("}")
        lines.append("")

        # agent → base class
        for a in agents:
            lines.append(f"{agent_base(a)} <|-- {a['name']}")
        lines.append("")

        # squad → BaseSquad, squad *-- agents
        for sq in squads:
            lines.append(f"BaseSquad <|-- {sq['name']}")
            for agent_name in sq.get("agents", []):
                lines.append(f"{sq['name']} *-- {agent_name}")
        if squads:
            lines.append("")

    # ── orchestrators ────────────────────────────────────────────────────
    if orchestrators:
        lines.append(f'package "{app_name} Orchestrators" {{')
        for o in orchestrators:
            lines.append(f"  class {o['name']}")
        lines.append("}")
        lines.append("")
        for o in orchestrators:
            lines.append(f"BaseOrchestrator <|-- {o['name']}")
            squad_name = o.get("squad")
            if squad_name:
                lines.append(f"{o['name']} ..> {squad_name} : loads")
        lines.append("")

    # ── legend: what the arrows/lines mean ──────────────────────────────
    lines.append("legend bottom right")
    lines.append("|= Notation |= Meaning |")
    lines.append("| ──▷ | Inheritance (extends) |")
    lines.append("| ──◆ | Composition (owns) |")
    lines.append("| ╌╌> | Dependency (uses) |")
    lines.append("endlegend")
    lines.append("")

    lines.append("@enduml")
    return "\n".join(lines)


_PLANTUML_ALPHABET = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz-_"


def _plantuml_deflate_encode(puml_source: str) -> str:
    """PlantUML's "deflate + custom base64" URL encoding (stdlib zlib, no new deps) — far more compact than `~h<hex>`, which exceeds the server's GET length limit for non-trivial diagrams."""
    compressor = zlib.compressobj(9, zlib.DEFLATED, -15)
    data = compressor.compress(puml_source.encode("utf-8")) + compressor.flush()

    def encode6bit(b: int) -> str:
        return _PLANTUML_ALPHABET[b & 0x3F]

    out = []
    for i in range(0, len(data), 3):
        b1 = data[i]
        b2 = data[i + 1] if i + 1 < len(data) else 0
        b3 = data[i + 2] if i + 2 < len(data) else 0
        out.append(encode6bit(b1 >> 2))
        out.append(encode6bit(((b1 & 0x3) << 4) | (b2 >> 4)))
        out.append(encode6bit(((b2 & 0xF) << 2) | (b3 >> 6)))
        out.append(encode6bit(b3 & 0x3F))
    return "".join(out)


def render_puml_to_png(puml_source: str, timeout: int = 10) -> Optional[bytes]:
    """
    Render PlantUML source to PNG via the PlantUML server's deflate-encoded
    URL. Best-effort: returns None on any failure (offline, server
    unreachable, non-image response) so the scaffold ZIP always succeeds even
    without the rendered PNG.
    """
    try:
        url = f"{PLANTUML_SERVER}/png/{_plantuml_deflate_encode(puml_source)}"
        resp = requests.get(url, timeout=timeout)
        resp.raise_for_status()
        if resp.headers.get("Content-Type", "").startswith("image/png"):
            return resp.content
        return None
    except Exception:
        return None


def generate_scaffold(project: dict) -> io.BytesIO:
    """
    Generate a K9-AIF scaffold ZIP from the studio project definition.

    project dict keys:
      project_name, author, domain, description,
      orchestrators: [{name, squad}],
      squads:        [{name, agents: [str]}],
      agents:        [{name, type, model, pattern, description}]
    """
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    app_name = to_pascal(project["project_name"])
    app_folder = to_snake(project["project_name"])
    author = project.get("author", "")
    domain = project.get("domain", "")

    agents_by_name = {a["name"]: a for a in project.get("agents", [])}
    squads = project.get("squads", [])
    orchestrators = project.get("orchestrators", [])

    # Project-local import check used by setup.sh/run.sh to verify the
    # exported scaffold is wired correctly (no k9_projects involved).
    if orchestrators:
        _import_lines = [
            f"from orchestrators.{to_snake(o['name'])} import {o['name']}"
            for o in orchestrators
        ]
        project_import_label = ", ".join(
            f"orchestrators.{to_snake(o['name'])}.{o['name']}" for o in orchestrators
        )
    else:
        _import_lines = ["import utils.agent_loader"]
        project_import_label = "utils.agent_loader"
    project_import_stmt = "; ".join(_import_lines) + '; print("project import ok")'

    zip_buf = io.BytesIO()

    with zipfile.ZipFile(zip_buf, mode="w", compression=zipfile.ZIP_DEFLATED) as zf:

        def add(path: str, content: str):
            info = zipfile.ZipInfo(path)
            info.compress_type = zipfile.ZIP_DEFLATED
            # Set executable bit for shell scripts
            if path.endswith(".sh"):
                info.external_attr = 0o755 << 16
            else:
                info.external_attr = 0o644 << 16
            zf.writestr(info, content)

        # ── agents ────────────────────────────────────────────────────
        for agent_def in project.get("agents", []):
            agent_name = agent_def["name"]
            agent_type = agent_def.get("type", "BaseAgent")
            snake = to_snake(agent_name)

            template_name = AGENT_TEMPLATE_MAP.get(agent_type, "agent_base.py.j2")
            py_code = _render(template_name, {
                "class_name": agent_name,
                "app_name": app_name,
                "timestamp": timestamp,
            })
            add(f"{app_folder}/agents/src/{snake}.py", py_code)

            yaml_code = _render("agent.yaml.j2", {
                "agent": agent_def,
                "domain": domain,
                "timestamp": timestamp,
            })
            add(f"{app_folder}/agents/yaml/{snake}.yaml", yaml_code)

        # ── __init__.py stubs ─────────────────────────────────────────
        for subdir in ("", "agents/src", "agents/yaml", "orchestrators", "config", "utils", "tests", "squads/src", "squads/yaml"):
            init_path = f"{app_folder}/{subdir}/__init__.py" if subdir else f"{app_folder}/__init__.py"
            add(init_path, f"# {app_name} — generated by k9x_studio\n")

        # ── test stub ─────────────────────────────────────────────────
        test_stub = f'''# SPDX-License-Identifier: Apache-2.0
# Generated by k9x_studio on {timestamp}

import pytest
from unittest.mock import patch, MagicMock


@pytest.fixture
def sample_payload():
    return {{"event_type": "{to_snake(app_name)}_event", "data": {{}}}}


# TODO: Add agent tests here
# Example:
# from {app_folder.replace("/", ".")}.agents.src.my_agent import MyAgent
# def test_my_agent(sample_payload):
#     agent = MyAgent(config={{}})
#     result = agent.execute(sample_payload)
#     assert "output" in result
'''
        add(f"{app_folder}/tests/test_{to_snake(app_name)}.py", test_stub)
        add(f"{app_folder}/tests/conftest.py", f'# pytest conftest for {app_name}\nimport pytest\n')

        # ── squads ────────────────────────────────────────────────────
        # One YAML per squad in squads/yaml/
        for squad in squads:
            squad_yaml = f"# SPDX-License-Identifier: Apache-2.0\n# Generated by k9x_studio on {timestamp}\n\nsquads:\n"
            squad_yaml += f"  {squad['name']}:\n"
            squad_yaml += f"    description: \"{squad['name']} agent pipeline — {domain}\"\n"
            squad_yaml += "    agents:\n"
            for a in squad["agents"]:
                squad_yaml += f"      - {a}\n"
            squad_yaml += "    flow:\n"
            for a in squad["agents"]:
                squad_yaml += f"      - agent: {a}\n"
                squad_yaml += f"        result_key: {to_snake(a)}\n"
            add(f"{app_folder}/squads/yaml/{to_snake(squad['name'])}.yaml", squad_yaml)

            # Squad src stub — extend BaseSquad only if custom behaviour needed
            squad_src = f'''# SPDX-License-Identifier: Apache-2.0
# Generated by k9x_studio on {timestamp}
# Extend BaseSquad only if you need custom squad behaviour.
# Default: SquadLoader wires agents from YAML — no code changes required.

from k9_aif_abb.k9_squad.base_squad import BaseSquad


class {squad['name']}(BaseSquad):
    """Squad: {squad['name']} — {domain}"""
    pass
'''
            add(f"{app_folder}/squads/src/{to_snake(squad['name'])}.py", squad_src)

        # Also write combined squads.yaml to config/ for backward compatibility
        all_squads_yaml = f"# SPDX-License-Identifier: Apache-2.0\n# Generated by k9x_studio on {timestamp}\n\nsquads:\n"
        for squad in squads:
            all_squads_yaml += f"  {squad['name']}:\n"
            all_squads_yaml += f"    description: \"{squad['name']} agent pipeline — {domain}\"\n"
            all_squads_yaml += "    agents:\n"
            for a in squad["agents"]:
                all_squads_yaml += f"      - {a}\n"
            all_squads_yaml += "    flow:\n"
            for a in squad["agents"]:
                all_squads_yaml += f"      - agent: {a}\n"
                all_squads_yaml += f"        result_key: {to_snake(a)}\n"
            all_squads_yaml += "\n"
        add(f"{app_folder}/config/squads.yaml", all_squads_yaml)

        # ── orchestrators ─────────────────────────────────────────────
        for orch_def in orchestrators:
            orch_name = orch_def["name"]
            squad_name = orch_def.get("squad", squads[0]["name"] if squads else "DefaultSquad")

            # collect agents for this squad
            squad_agents = []
            for sq in squads:
                if sq["name"] == squad_name:
                    squad_agents = sq["agents"]
                    break

            orch_code = _render("orchestrator.py.j2", {
                "app_name": app_name,
                "app_folder": app_folder,
                "orchestrator_name": orch_name,
                "squad_name": squad_name,
                "agent_names": squad_agents,
                "timestamp": timestamp,
            })
            add(f"{app_folder}/orchestrators/{to_snake(orch_name)}.py", orch_code)

        # ── config.yaml — reuse canonical generator template ─────────
        import os as _os2
        ollama_base_url = (
            project.get("ollama_base_url", "").strip()
            or _os2.environ.get("OLLAMA_BASE_URL", "http://localhost:11434")
        )
        # Reflect Studio palette selections (Platforms & Frameworks) into
        # config.yaml so the SBB knows what to wire up.
        platforms = project.get("platforms", [])
        agent_frameworks = [p for p in platforms if not p.startswith("watsonx-")]
        ibm_watsonx = [p for p in platforms if p.startswith("watsonx-")]
        messaging = [m for m in project.get("messaging_list", []) if m and m != "None"]
        databases = [d for d in project.get("database_list", []) if d and d != "None"]
        deployment_targets = [d for d in project.get("deployment_list", []) if d]

        config_yaml = _render("config.yaml.j2", {
            "app_name": app_name,
            "app_folder": app_folder,
            "author": author,
            "domain": domain,
            "timestamp": timestamp,
            "ollama_base_url": ollama_base_url,
            "agent_frameworks": agent_frameworks,
            "ibm_watsonx": ibm_watsonx,
            "messaging": messaging,
            "databases": databases,
            "deployment_targets": deployment_targets,
        })
        add(f"{app_folder}/config/config.yaml", config_yaml)

        # ── config/scenario.json — "best case" demo scenario ───────────
        # main.py prints title + narrative, then sends `payload` to the
        # squad as its input. Empty dict if the project has none — main.py
        # falls back to its generic placeholder payload in that case.
        scenario = project.get("scenario") or {}
        add(f"{app_folder}/config/scenario.json", json.dumps(scenario, indent=2) + "\n")

        # ── main.py ───────────────────────────────────────────────────
        main_py = _render("main.py.j2", {
            "app_name": app_name,
            "app_folder": app_folder,
            "domain": domain,
            "orchestrators": orchestrators,
            "timestamp": timestamp,
        })
        add(f"{app_folder}/main.py", main_py)

        # ── utils/agent_loader.py ─────────────────────────────────────
        agent_loader_py = f'''# SPDX-License-Identifier: Apache-2.0
# Generated by k9x_studio on {timestamp}

import yaml
from pathlib import Path
from typing import Any, Dict


class AgentLoader:
    """Merges per-agent YAML with the global config dict."""

    def __init__(self, agents_yaml_dir: Path):
        self._dir = Path(agents_yaml_dir)
        self._cache: Dict[str, dict] = {{}}

    def _load(self, agent_name: str) -> dict:
        if agent_name not in self._cache:
            snake = "_".join(
                p.lower() for p in __import__("re").sub(
                    r"([a-z0-9])([A-Z])", r"\\1_\\2",
                    __import__("re").sub(r"(.)([A-Z][a-z]+)", r"\\1_\\2", agent_name)
                ).split("_")
            )
            path = self._dir / f"{{snake}}.yaml"
            if path.exists():
                with open(path) as f:
                    self._cache[agent_name] = yaml.safe_load(f) or {{}}
            else:
                self._cache[agent_name] = {{}}
        return self._cache[agent_name]

    def merge_with_global(self, agent_name: str, global_config: dict) -> dict:
        merged = dict(global_config)
        merged.update(self._load(agent_name))
        return merged
'''
        add(f"{app_folder}/utils/agent_loader.py", agent_loader_py)

        # ── .env ─────────────────────────────────────────────────────
        framework_path = project.get("framework_path", "").strip()

        env_lines = [
            f"# {app_name} — environment configuration",
            f"# Generated by k9x_studio on {timestamp}",
            "",
            "# K9-AIF Framework",
        ]
        if framework_path:
            # Ensure absolute path — strip accidental leading tilde for clarity
            fp = framework_path.lstrip()
            if not fp.startswith('/') and not fp.startswith('~'):
                fp = '/' + fp
            env_lines += [
                f'K9_FRAMEWORK_PATH="{fp}"',
            ]
        else:
            env_lines += [
                '# K9_FRAMEWORK_PATH="/path/to/k9-aif-framework"  # set this',
            ]
        env_lines += [
            "",
            "# LLM — Ollama (default)",
            'OLLAMA_BASE_URL="http://localhost:11434"',
            "",
            "# LLM — OpenAI (uncomment if using OpenAI backend in config.yaml)",
            '# OPENAI_API_KEY="sk-..."',
            "",
            "# LLM — Grok / xAI (uncomment if using Grok backend in config.yaml)",
            '# GROK_API_KEY="xai-..."',
            "",
            "# Advanced / optional infrastructure — not used by this scaffold's",
            "# config.yaml. Uncomment if you extend it with Kafka, Postgres, Neo4j,",
            "# or Redis (see the EOC example in k9-aif-framework/examples/ for a",
            "# config.yaml that wires these in).",
            '# KAFKA_BROKER="localhost:9092"',
            '# POSTGRES_HOST="localhost"',
            '# POSTGRES_USER="postgres"',
            f'# POSTGRES_DB="{app_folder}"',
            '# K9_PG_PASSWORD=""',
            '# NEO4J_URI="bolt://localhost:7687"',
            '# NEO4J_USER="neo4j"',
            '# NEO4J_PASSWORD=""',
            '# REDIS_HOST="localhost"',
            '# REDIS_PORT="6379"',
            '# REDIS_PASSWORD=""',
            "",
            "# App",
            f'APP_NAME="{app_name}"',
            f'APP_DOMAIN="{domain}"',
        ]
        add(f"{app_folder}/.env", "\n".join(env_lines) + "\n")

        # ── .env.example ──────────────────────────────────────────────
        env_example_lines = [
            f"# {app_name} — environment variable reference",
            f"# Copy to .env and fill in values. Never commit .env to source control.",
            f"# Generated by k9x_studio on {timestamp}",
            "",
            "# ── K9-AIF Framework path ────────────────────────────────",
            "# Absolute path to your k9-aif-framework clone.",
            "# Do not use ~ — use the full path.",
            'K9_FRAMEWORK_PATH=',
            "",
            "# ── LLM — Ollama (default, local, no key needed) ─────────",
            'OLLAMA_BASE_URL=http://localhost:11434',
            "",
            "# ── LLM — OpenAI ─────────────────────────────────────────",
            "# Set backend: openai and api_key_env: OPENAI_API_KEY in config.yaml",
            'OPENAI_API_KEY=',
            "",
            "# ── LLM — Grok / xAI ─────────────────────────────────────",
            "# Set backend: openai-compatible and api_key_env: GROK_API_KEY in config.yaml",
            'GROK_API_KEY=',
            "",
            "# ── Advanced / optional infrastructure ───────────────────",
            "# Not used by this scaffold's config.yaml. Uncomment if you extend",
            "# it with Kafka, Postgres, Neo4j, or Redis — see the EOC example",
            "# in k9-aif-framework/examples/ for a config.yaml that wires these in.",
            "# KAFKA_BROKER=localhost:9092",
            "# POSTGRES_HOST=localhost",
            "# POSTGRES_USER=postgres",
            f"# POSTGRES_DB={app_folder}",
            "# K9_PG_PASSWORD=",
            "# NEO4J_URI=bolt://localhost:7687",
            "# NEO4J_USER=neo4j",
            "# NEO4J_PASSWORD=",
            "# REDIS_HOST=localhost",
            "# REDIS_PORT=6379",
            "# REDIS_PASSWORD=",
            "",
            "# ── App ──────────────────────────────────────────────────",
            f'APP_NAME={app_name}',
            f'APP_DOMAIN={domain}',
        ]
        add(f"{app_folder}/.env.example", "\n".join(env_example_lines) + "\n")

        # ── requirements.txt — project-level deps. k9_aif_abb and its own
        # deps come from K9_FRAMEWORK_PATH/requirements.txt, installed by
        # setup.sh — not duplicated here. ───────────────────────────────
        requirements_txt = f"""# {app_name} — Python dependencies for this scaffold
# Generated by k9x_studio on {timestamp}
#
# k9_aif_abb and its dependencies are provided by the k9-aif-framework
# pointed to by K9_FRAMEWORK_PATH in .env — its own requirements.txt is
# installed separately by setup.sh.

pyyaml>=6.0
"""
        add(f"{app_folder}/requirements.txt", requirements_txt)

        # ── run.sh / setup.sh — self-contained, no k9_projects ──────────
        shell_ctx = {
            "app_name": app_name,
            "app_folder": app_folder,
            "timestamp": timestamp,
            "framework_repo_url": FRAMEWORK_REPO_URL,
            "project_import_stmt": project_import_stmt,
            "project_import_label": project_import_label,
        }
        add(f"{app_folder}/run.sh", _render("run.sh.j2", shell_ctx))
        add(f"{app_folder}/setup.sh", _render("setup.sh.j2", shell_ctx))

        # ── CLAUDE.md — just imports the framework's CLAUDE.md ───────
        fw_ref = framework_path if framework_path else "/path/to/k9-aif-framework"
        claude_md = f"@{fw_ref}/CLAUDE.md\n"
        add(f"{app_folder}/CLAUDE.md", claude_md)

        # ── README ────────────────────────────────────────────────────
        llm_provider = project.get('llm_provider', '')
        llm_model    = project.get('llm_model', '')
        gen_source   = project.get('generation_source', '')
        scoring      = project.get('generation_scoring') or {}
        llm_line     = f"{llm_provider} · {llm_model}" if llm_model else "—"
        source_line  = gen_source if gen_source else "rule-based"
        score_line   = ""
        if scoring:
            winner = scoring.get('winner', '')
            ws     = scoring.get(winner, {})
            ls     = scoring.get('llm' if winner == 'rule_based' else 'rule_based', {})
            score_line = f" (winner score: {ws.get('score','?')} vs {ls.get('score','?')})"

        readme = f"""# {app_name}

| | |
|---|---|
| **Studio** | [studio.k9x.ai](https://studio.k9x.ai) |
| **Framework** | [k9x.ai](https://k9x.ai) — K9-AIF Architecture-First |
| **Generated** | {timestamp} |
| **Author** | {author or '—'} |
| **LLM** | {llm_line} |
| **Generation** | {source_line}{score_line} |

---

**Domain:** {domain}
**Description:** {project.get('description', '')}

## Quick start

```bash
unzip {app_folder}.zip
cd {app_folder}

./setup.sh                      # one-time: venv, framework path, deps, .env
source .venv/bin/activate       # if setup.sh created .venv/ for you
./run.sh
```

`setup.sh` walks you through:

- creating (or using) a Python virtual environment
- pointing at — or cloning — a `k9-aif-framework` checkout
- installing this project's and the framework's dependencies
- writing `K9_ENV` and `K9_FRAMEWORK_PATH` into `.env`

Run `./setup.sh --verify` at any time to re-check the environment.

## Recommended workspace layout

```
workspace/
├── {app_folder}/        <- this project (unzipped here)
└── k9-aif-framework/      <- sibling clone (setup.sh option 2)
```

If you already have a `k9-aif-framework` checkout elsewhere, point `setup.sh`
at it instead (option 1) — it sets `K9_FRAMEWORK_PATH` in `.env` accordingly.

This scaffold is self-contained: `setup.sh` and `run.sh` work directly from
this folder, with no dependency on the canonical generator's project-nesting
layout.

## Prerequisites

- Python 3.11 or 3.12 (avoid 3.14 — `venv`/`ensurepip` issues)
- A `k9-aif-framework` checkout (existing, or let `setup.sh` clone one)
- Ollama running at http://localhost:11434, with these models pulled:

  ```bash
  ollama pull llama3.2:1b        # "general" model — used by BaseAgent steps
  ollama pull granite3-dense:2b  # "reasoning" model — used by K9ValidationLoopAgent
                                  # and K9CriticActorAgent steps
  ```

  If a model isn't pulled, Ollama returns an error that gets passed through
  as the agent's "response" text (e.g. `[WARN] Ollama HTTP 404 | model=...`)
  instead of a clear failure — agents will run but produce garbage output.
  Run `ollama list` to check what's already available.

## Structure

```
{app_folder}/
├── agents/src/       # Agent Python classes
├── agents/yaml/      # Agent configuration
├── orchestrators/    # Orchestrator classes
├── config/           # config.yaml + squads.yaml
├── utils/            # agent_loader.py
├── main.py           # Entry point
├── setup.sh          # One-time environment setup (venv, framework, deps, .env)
├── run.sh            # Launch script
├── requirements.txt  # Project-level Python dependencies
├── .env              # K9_ENV, K9_FRAMEWORK_PATH (written by setup.sh)
└── CLAUDE.md         # Claude Code context
```

## Troubleshooting

**`ModuleNotFoundError: No module named 'k9_aif_abb'`**
`K9_FRAMEWORK_PATH` in `.env` doesn't point at a valid `k9-aif-framework`
checkout, or its `requirements.txt` isn't installed. Run `./setup.sh --verify`
to check, or `./setup.sh` to fix it.

**`ModuleNotFoundError: No module named 'orchestrators'`** (or `agents`, `utils`)
`run.sh`/`setup.sh` add this project's folder to `PYTHONPATH` automatically.
If you're running `python3 main.py` directly, `cd` into this folder first so
its `PYTHONPATH` entry resolves, or use `./run.sh`.

**Wrong `K9_FRAMEWORK_PATH`**
Edit `.env` directly, or re-run `./setup.sh` and choose the correct option
(existing folder vs. clone). Paths may be absolute or relative to this
project's folder (e.g. `../k9-aif-framework`).

**Python 3.14 `venv`/`ensurepip` errors**
`setup.sh` prefers `python3.12`/`python3.11` when creating `.venv/`. If only
Python 3.14+ is available, install 3.12 or 3.11 and re-run `./setup.sh`.

**No virtual environment active**
`./setup.sh` offers to create `.venv/` for you, or lets you activate your own.
After creating one, run `source .venv/bin/activate && ./setup.sh --continue`.

**`requirements.txt` install failed**
Re-run `./setup.sh` after fixing the underlying issue (network access,
compiler toolchain for native deps, etc.) — `pip install --upgrade pip
setuptools wheel` runs first to reduce build issues.
"""
        add(f"{app_folder}/README.md", readme)

        # ── diagrams/ — class diagram (PlantUML source + rendered PNG) ──
        class_diagram_puml = generate_class_diagram_puml(project, app_name, app_folder, timestamp)
        add(f"{app_folder}/diagrams/{app_folder}_class_diagram.puml", class_diagram_puml)

        png_bytes = render_puml_to_png(class_diagram_puml)
        if png_bytes:
            png_info = zipfile.ZipInfo(f"{app_folder}/diagrams/{app_folder}_class_diagram.png")
            png_info.compress_type = zipfile.ZIP_DEFLATED
            png_info.external_attr = 0o644 << 16
            zf.writestr(png_info, png_bytes)

    zip_buf.seek(0)
    return zip_buf
