# SPDX-License-Identifier: Apache-2.0
# Static catalog of what the K9-AIF framework already implements out of the
# box, mapped to the Process Studio eval-plan categories/rows that ask for
# it — so an SA sees "the framework already does this" instead of writing
# logic the framework ships for free. Two sources so far:
#   - Adversarial Evals -> k9x_Shield's 13 vulnerability checks
#     (k9_aif_abb/k9_security/vulnerability/checks/)
#   - Behavioral Evals -> the ValidationLoop/CriticActor HITL-escalation
#     patterns (K9ValidationLoopAgent, K9CriticActorAgent)
#
# Verified against real source, not guessed from names:
#   1. Each check's own docstring in k9-aif-framework.
#   2. k9x_satan's 13 attack modules (k9x-ecosystem/k9x_satan/attacks/),
#      each of which states its target check in its own docstring. NOTE
#      (2026-09-19): search_poisoning_attack.py's own docstring claims
#      "Targets: Router ingress PromptInjectionCheck", but running the
#      actual attack live (twice, independently) shows it is NOT
#      contained — PromptInjectionCheck only runs at ingress, before the
#      poisoned search-tool response even exists (it arrives mid-execution,
#      during agent runtime, not in the original payload). The docstring
#      states an intended target, not verified live behavior — don't trust
#      an attack module's own docstring as proof of containment without
#      running it. See ADVERSARIAL_COVERAGE's "Poisoned tool / MCP
#      response" entry below, corrected to match the live result.
#   3. implementation-plan.md's own "Patterns Applied" section (generated by
#      scaffold_service.py from the same source data): ValidationLoop's
#      should_continue threshold logic is real generated code; CriticActor's
#      critique() is explicitly a TODO stub — that asymmetry is exactly why
#      RED is "partial" below, not "covered".
#
# Single source of truth for the Evals tab's Framework Coverage column
# (evals_service.parse_evals) and the generated test docstrings
# (scaffold_service._gen_eval_test_files) — see each call site.

import re

SHIELD_CHECKS: dict[str, dict] = {
    "PromptInjectionCheck": {
        "gate": "ingress",
        "action": "BLOCK",
        "description": "Detects prompt injection / instruction-override attempts in payload strings — "
                        "same scan applies to tool-response content, not just uploaded documents.",
    },
    "OutputSanitizationCheck": {
        "gate": "egress",
        "action": "BLOCK",
        "description": "Detects markup/script/template injection patterns in agent output before it exits the pipeline.",
    },
    "ExecutionGuardCheck": {
        "gate": "egress",
        "action": "BLOCK",
        "description": "Final guardrail for destructive execution payloads — filesystem destruction, reverse "
                        "shells, privilege escalation, persistence, dangerous interpreter invocations.",
    },
    "ToolAuthorizationCheck": {
        "gate": "ingress",
        "action": "BLOCK",
        "description": "Detects unapproved tools or tool backends before a tool call is dispatched — blocks "
                        "any tool_name or backend URL not on the allowlist.",
    },
    "ToolArgumentCheck": {
        "gate": "ingress",
        "action": "BLOCK",
        "description": "Inspects LLM-generated tool call arguments before execution — SQL injection, command "
                        "injection, path traversal, SSRF.",
    },
    "MemoryPoisoningCheck": {
        "gate": "ingress",
        "action": "BLOCK",
        "description": "Detects fabricated or contradicted session memory via a fact fingerprint — blocks a "
                        "payload that claims a prior state not in the cache, or contradicts recorded facts.",
    },
    "SystemPromptLeakageCheck": {
        "gate": "egress",
        "action": "BLOCK",
        "description": "Detects verbatim system-prompt fragments in agent output — a leaked system prompt "
                        "hands an attacker the exact wording for a more precise injection next time.",
    },
    "RequestFrequencyCheck": {
        "gate": "ingress",
        "action": "BLOCK",
        "description": "Enforces a per-session request budget within a rolling time window.",
    },
    "InputSizeCheck": {
        "gate": "ingress",
        "action": "BLOCK",
        "description": "Enforces maximum payload size to prevent token-stuffing and DoS via the LLM.",
    },
    "HardcodedCredentialCheck": {
        "gate": "egress",
        "action": "BLOCK",
        "description": "Detects hardcoded credentials, API keys, and secrets in payload string values.",
    },
    "SemanticDriftCheck": {
        "gate": "egress",
        "action": "BLOCK",
        "description": "Detects system goal hijacking phrases and loop trap patterns.",
    },
    "PIIBoundaryCheck": {
        "gate": "egress",
        "action": "FLAG",
        "description": "Detects PII (email, SSN, credit card, phone) actually present in payload values — "
                        "non-blocking by default, recorded for audit.",
    },
    "PIIRequestCheck": {
        "gate": "ingress",
        "action": "BLOCK",
        "description": "Detects a request/instruction soliciting disclosure of sensitive fields — catches the "
                        "ask, not just the leak.",
    },
}

# Keyed by the Adversarial-Evals category label exactly as Process Studio's
# blueprint methodology states it (the text before " — <Agent Name>" in each
# row's Scenario column — see evals_service.py). None of these are guessed:
# each is backed by a k9x_satan attack module's own "Targets:" docstring, or
# (where noted) is explicitly NOT a Shield check at all.
ADVERSARIAL_COVERAGE: dict[str, dict] = {
    "Prompt injection (direct + tool-output indirect)": {
        "checks": ["PromptInjectionCheck"], "status": "covered", "note": None,
    },
    "Insecure output handling": {
        "checks": ["OutputSanitizationCheck"], "status": "covered", "note": None,
    },
    "Training-data or memory exfiltration": {
        "checks": ["MemoryPoisoningCheck", "SystemPromptLeakageCheck"], "status": "covered", "note": None,
    },
    "Model DoS (token bomb / recursive calls)": {
        "checks": ["InputSizeCheck", "RequestFrequencyCheck"], "status": "covered", "note": None,
    },
    "Poisoned tool / MCP response": {
        "checks": ["PromptInjectionCheck"], "status": "partial",
        "note": "Not actually contained today, confirmed by running k9x_satan's own "
                "search_poisoning_attack live (twice, independently, 2026-09-19) — the attack module's own "
                "docstring claims this check catches it, but PromptInjectionCheck only runs at ingress, "
                "before a poisoned tool response exists (it arrives mid-execution, not in the original "
                "payload). Closing this gap needs an egress-time (or mid-execution) prompt-injection check, "
                "not just the ingress one. Listed as the only check that could plausibly cover it once wired "
                "correctly, not because it does today.",
    },
    "Sensitive information disclosure in prompt": {
        "checks": ["PIIRequestCheck"], "status": "covered", "note": None,
    },
    "Insecure plugin / unbounded tool call": {
        "checks": ["ToolAuthorizationCheck", "ToolArgumentCheck"], "status": "covered", "note": None,
    },
    "Excessive agency / unauthorized write": {
        "checks": ["ExecutionGuardCheck"], "status": "covered", "note": None,
    },
    "Overreliance (no HITL on RED)": {
        # Not a Shield check — this is the same underlying mechanism as the
        # Behavioral RED row below (K9CriticActorAgent.should_accept), asked
        # from a different angle (Adversarial: "does the agent overrely on
        # itself" vs Behavioral: "does the autonomy contract hold"). Linked
        # rather than left unmapped so the two don't read as two separate
        # gaps when they're one.
        "checks": ["K9CriticActorAgent.should_accept"], "status": "partial",
        "note": "Same mechanism as the Behavioral RED autonomy-contract check — the ESCALATE decision "
                "plumbing is framework-provided, but critique()'s domain judgment is a TODO stub.",
    },
    "Model theft via prompt mirroring": {
        "checks": ["SystemPromptLeakageCheck"], "status": "covered", "note": None,
    },
}

# Non-Shield framework patterns — a different kind of "already covered" than
# the Adversarial checks above (a class/method, not a chain handler with a
# gate/action), so these carry a description only, no gate/action.
FRAMEWORK_PATTERNS: dict[str, dict] = {
    "K9ValidationLoopAgent.should_continue": {
        "description": "Confidence-threshold ESCALATE path: confidence >= threshold -> FINALIZE; "
                        "iteration >= max_iterations AND confidence < 0.3 -> ESCALATE to human review. "
                        "Real generated code in every AMBER-zone agent, not a stub.",
    },
    "K9CriticActorAgent.should_accept": {
        "description": "ACCEPTED/REJECTED/ESCALATE/FAIL decision plumbing is framework-provided, but the "
                        "domain judgment inside critique() is a TODO stub — see implementation-plan.md's "
                        "Patterns Applied section.",
    },
}

# Keyed by zone, parsed from the Behavioral Evals scenario text itself
# ("AMBER step autonomy contract: ..." / "RED step autonomy contract: ...")
# — Process Studio doesn't give zone its own column here, unlike the BPMN.
_BEHAVIORAL_ZONE_PATTERN = re.compile(r"^(AMBER|RED)\s+step autonomy contract", re.I)

BEHAVIORAL_COVERAGE: dict[str, dict] = {
    "AMBER": {
        "checks": ["K9ValidationLoopAgent.should_continue"], "status": "covered",
        "note": "Fully covered — should_continue's threshold logic is real, generated code today, not a TODO.",
    },
    "RED": {
        "checks": ["K9CriticActorAgent.should_accept"], "status": "partial",
        "note": "Partially covered — the ESCALATE decision plumbing is framework-provided, but critique()'s "
                "actual judgment is a TODO stub. Implement a real domain validator before trusting this "
                "test's Pass Criteria.",
    },
}


def _details_for(names: list[str]) -> list[dict]:
    """Look up each name in whichever catalog has it — a Shield check (has
    gate/action) or a non-Shield framework pattern (description only, e.g.
    the Overreliance/Behavioral RED entries pointing at
    K9CriticActorAgent.should_accept)."""
    out = []
    for name in names:
        if name in SHIELD_CHECKS:
            out.append({"name": name, **SHIELD_CHECKS[name]})
        elif name in FRAMEWORK_PATTERNS:
            out.append({"name": name, **FRAMEWORK_PATTERNS[name]})
    return out


def _adversarial_coverage(scenario: str) -> dict | None:
    label = (scenario or "").split(" — ", 1)[0].strip()
    entry = ADVERSARIAL_COVERAGE.get(label)
    if entry is None:
        return None
    return {
        "checks": entry["checks"],
        "status": entry["status"],
        "note": entry["note"],
        "details": _details_for(entry["checks"]),
    }


def _behavioral_coverage(scenario: str) -> dict | None:
    m = _BEHAVIORAL_ZONE_PATTERN.match((scenario or "").strip())
    if not m:
        return None
    entry = BEHAVIORAL_COVERAGE.get(m.group(1).upper())
    if entry is None:
        return None
    return {
        "checks": entry["checks"],
        "status": entry["status"],
        "note": entry["note"],
        "details": _details_for(entry["checks"]),
    }


def coverage_for_row(category: str, scenario: str) -> dict | None:
    """Look up framework coverage for one eval-plan row. Only Adversarial
    and Behavioral rows resolve to anything — every other category returns
    None, not a guess. Returned shape is uniform across both:
    {checks: [str], status: "covered"|"partial"|"not_applicable", note: str|None, details: [dict]}.
    """
    if category == "adversarial":
        return _adversarial_coverage(scenario)
    if category == "behavioral":
        return _behavioral_coverage(scenario)
    return None
