export function AboutStudio() {
  return (
    <div style={{ maxWidth: 640, padding: '4px 0' }}>
      <div style={{ marginBottom: 32 }}>
        <div style={{ fontSize: 22, fontWeight: 700, color: 'var(--text)', marginBottom: 4 }}>
          K9X Studio
        </div>
        <div style={{ fontSize: 14, color: '#6366f1', fontStyle: 'italic', marginBottom: 16 }}>
          Not just agents — architecture.
        </div>
        <div style={{ fontSize: 13, color: '#94a3b8', lineHeight: 1.8 }}>
          K9X Studio is a visual drag-and-drop workbench for designing K9-AIF compliant
          multi-agent architectures — upload a spec doc, generate the canvas, download the scaffold.
        </div>
      </div>

      {/* Workflow */}
      <div style={{
        marginBottom: 28, padding: '12px 16px',
        background: 'rgba(99,102,241,0.06)', border: '1px solid #2a2d3e', borderRadius: 8,
        fontSize: 13, color: '#94a3b8', lineHeight: 2,
      }}>
        <span style={{ color: '#6366f1', fontWeight: 600 }}>How to use: </span>
        <span style={{ color: '#a5b4fc' }}>Setup LLM</span>
        <span style={{ color: '#475569' }}> → </span>
        <span>Upload Spec Doc or BPMN</span>
        <span style={{ color: '#475569' }}> → </span>
        <span>Canvas auto-generates</span>
        <span style={{ color: '#475569' }}> → </span>
        <span style={{ color: '#10b981', fontWeight: 600 }}>⬇ Generate Scaffold</span>
      </div>

      {/* What it does */}
      <div style={{ marginBottom: 28 }}>
        <div style={{ fontSize: 13, fontWeight: 600, color: 'var(--text)', marginBottom: 12, textTransform: 'uppercase', letterSpacing: '1px' }}>
          What it does
        </div>
        {[
          ['📄', 'Upload Spec Doc',    'Upload a project spec .md (Process Studio output) — canvas auto-generates with Router, Orchestrators, Squads, Agents.'],
          ['🔵', 'Upload BPMN',        'Upload IBM Blueworks Live, Camunda, or Bizagi BPMN exports — canvas auto-generates from the process flow.'],
          ['🎨', 'Visual Canvas',      'Drag-and-drop K9-AIF components. Connect Router → Orchestrator → Squad → Agents visually.'],
          ['📐', 'Templates',          'Start from pre-built templates: Insurance, Finance, Healthcare, Customer Service, and more.'],
          ['⬇',  'Generate Scaffold',  'Download a ready-to-run K9-AIF project ZIP with all boilerplate generated.'],
        ].map(([icon, title, desc]) => (
          <div key={title as string} style={{ display: 'flex', gap: 12, marginBottom: 12, padding: '10px 14px', background: 'var(--surface)', border: '1px solid var(--border)', borderRadius: 8 }}>
            <span style={{ fontSize: 18 }}>{icon}</span>
            <div>
              <div style={{ fontSize: 13, fontWeight: 500, color: 'var(--text)' }}>{title as string}</div>
              <div style={{ fontSize: 12, color: '#94a3b8' }}>{desc as string}</div>
            </div>
          </div>
        ))}
      </div>

      {/* How canvas is generated */}
      <div style={{ marginBottom: 28 }}>
        <div style={{ fontSize: 13, fontWeight: 600, color: 'var(--text)', marginBottom: 12, textTransform: 'uppercase', letterSpacing: '1px' }}>
          How the Canvas is Generated
        </div>
        <div style={{ fontSize: 12, color: '#94a3b8', lineHeight: 1.8, marginBottom: 8 }}>
          The studio uses a <strong style={{ color: '#c8d0de' }}>layered approach</strong> to generate the architecture canvas. The backend has built-in rules to decide when the LLM needs to be used — and when it doesn't. If you don't see the processing overlay, it means the canvas was generated instantly using rule-based logic, which is by design.
        </div>
        {[
          ['1', 'Structured spec document (.md)', 'The spec doc contains section 3.1.8 Agent Definition Register — a table with agent names, zones (GREEN/AMBER/RED), and patterns. Generated by enterprise architecture tools, process modelers, or hand-crafted. The parser extracts agents directly and groups by zone. No LLM required. Deterministic and instant.', '#10b981'],
          ['2', 'LLM grouping (optional, when configured)', 'If an LLM is configured and the spec has structured agents, the LLM is asked to group them semantically into squads. Both the LLM result and rule-based result are scored — the richer output wins. If LLM returns fewer agents than expected, rule-based is used.', '#6366f1'],
          ['3', 'Unstructured doc / Intake Form', 'If no section 3.1.8 is found (e.g. a Project Intake Form), the LLM generates agents from the project description. Result quality depends on the model and description richness.', '#f59e0b'],
          ['4', 'BPMN / template / manual', 'BPMN uploads extract tasks from process flows. Templates use hand-designed architectures. Manual entry uses the intake fields with LLM or rule-based defaults.', '#8b5cf6'],
        ].map(([num, title, desc, color]) => (
          <div key={num as string} style={{ display: 'flex', gap: 12, marginBottom: 12, marginTop: 8, padding: '10px 14px', background: 'var(--surface)', border: '1px solid var(--border)', borderRadius: 8 }}>
            <div style={{ width: 22, height: 22, borderRadius: '50%', background: color as string, color: '#fff', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 11, fontWeight: 700, flexShrink: 0, marginTop: 1 }}>{num as string}</div>
            <div>
              <div style={{ fontSize: 12, fontWeight: 600, color: '#c8d0de', marginBottom: 3 }}>{title as string}</div>
              <div style={{ fontSize: 11, color: '#64748b', lineHeight: 1.6 }}>{desc as string}</div>
            </div>
          </div>
        ))}
      </div>

      {/* LLM note */}
      <div style={{ marginBottom: 28 }}>
        <div style={{ fontSize: 13, fontWeight: 600, color: 'var(--text)', marginBottom: 12, textTransform: 'uppercase', letterSpacing: '1px' }}>
          Architecture Standards & LLM
        </div>
        <div style={{ fontSize: 12, color: '#94a3b8', lineHeight: 1.8, marginBottom: 10 }}>
          The canvas always follows <strong style={{ color: '#c8d0de' }}>K9-AIF architecture standards</strong> — Router → Orchestrator → Squad → Agent hierarchy, with zone-based agent classification (GREEN / AMBER / RED).<br/><br/>
          When an LLM is configured, it interprets the uploaded spec and groups agents into squads. The <strong style={{ color: '#c8d0de' }}>flow on the canvas may differ depending on the LLM chosen</strong> — a stronger model produces richer, more contextual groupings. A weaker model may return fewer agents or incomplete structure, in which case the system falls back to rule-based grouping.
        </div>
        {[
          ['✓ Best',     'Claude Haiku / Sonnet / Opus',      'Reliable JSON, consistent groupings every run — recommended for production use'],
          ['✓ Good',     'qwen2.5:7b or 13b+ instruct',       'Strong JSON output, good squad grouping. 13b+ gives more consistent results than 7b'],
          ['⚠ Limited', 'granite3.3:8b (reasoning model)',   'Reasoning model, not optimised for JSON generation — inconsistent squad groupings'],
          ['✗ Avoid',   'granite-code / code models',         'Code generation models — not designed for architecture analysis or JSON structuring'],
          ['✗ Avoid',   'Models under 7B',                    'Too small for structured JSON output — falls back to rule-based automatically'],
        ].map(([badge, model, desc]) => (
          <div key={model as string} style={{ display: 'flex', gap: 12, marginBottom: 8, padding: '8px 12px', background: 'var(--surface)', border: '1px solid var(--border)', borderRadius: 6 }}>
            <span style={{ fontSize: 11, color: (badge as string).startsWith('✓') ? '#10b981' : '#f59e0b', flexShrink: 0, marginTop: 1 }}>{badge as string}</span>
            <div>
              <div style={{ fontSize: 12, fontWeight: 500, color: 'var(--text)' }}>{model as string}</div>
              <div style={{ fontSize: 11, color: '#64748b' }}>{desc as string}</div>
            </div>
          </div>
        ))}
      </div>

      {/* K9X Ecosystem */}
      <div style={{ marginBottom: 28 }}>
        <div style={{ fontSize: 13, fontWeight: 600, color: 'var(--text)', marginBottom: 12, textTransform: 'uppercase', letterSpacing: '1px' }}>
          K9X Ecosystem
        </div>
        {[
          ['studio.k9x.ai',    'This tool — visual K9-AIF designer', true],
          ['k9x-modernize',    'Reverse-engineer legacy code → K9-AIF blueprint → feed into Studio', false],
          ['graph.k9x.ai',     'Neo4j graph explorer for K9-AIF architectures', false],
          ['k9-aif-framework', 'The K9-AIF ABB library — BaseAgent, K9ValidationLoopAgent, K9CriticActorAgent, BaseGovernance', false],
        ].map(([name, desc, highlight]) => (
          <div key={name as string} style={{ display: 'flex', gap: 12, marginBottom: 8, fontSize: 12 }}>
            <span style={{ color: highlight ? '#34d399' : '#6366f1', minWidth: 160, fontWeight: highlight ? 600 : 500 }}>{name as string}</span>
            <span style={{ color: '#94a3b8' }}>{desc as string}</span>
          </div>
        ))}
      </div>

      {/* How the studio itself is built */}
      <div style={{ marginBottom: 28 }}>
        <div style={{ fontSize: 13, fontWeight: 600, color: 'var(--text)', marginBottom: 12, textTransform: 'uppercase', letterSpacing: '1px' }}>
          How This Studio Is Built
        </div>
        <div style={{ fontSize: 12, color: '#94a3b8', lineHeight: 1.8, marginBottom: 12 }}>
          K9X Studio doesn't just help you design K9-AIF architectures — it is one. It runs{' '}
          <span style={{ color: '#a5b4fc' }}>pip install k9-aif</span> to pull in the published{' '}
          <span style={{ color: '#a5b4fc' }}>k9_aif_abb</span> framework package and builds its
          own router and agent layers — <span style={{ color: '#a5b4fc' }}>studio_core</span> /{' '}
          <span style={{ color: '#a5b4fc' }}>studio_agents</span> — directly on top of it.
        </div>
        <div style={{ fontSize: 12, color: '#94a3b8', lineHeight: 1.8, marginBottom: 12 }}>
          The spec-import flow you just used — upload a doc, get a canvas — runs as a real
          K9-AIF squad: <span style={{ color: '#a5b4fc' }}>GovernanceAgent</span> screens the
          document, then <span style={{ color: '#a5b4fc' }}>SpecParserAgent</span> spawns three
          sub-agents in parallel (project info, agent table, zone mapping) via{' '}
          <span style={{ color: '#a5b4fc' }}>K9SubAgentSpawner</span>, and{' '}
          <span style={{ color: '#a5b4fc' }}>LLMGroupingAgent</span> /{' '}
          <span style={{ color: '#a5b4fc' }}>ScoringAgent</span> /{' '}
          <span style={{ color: '#a5b4fc' }}>CanvasBuilderAgent</span> assemble the suggested
          architecture you see on the canvas.
        </div>
        <a
          href="/architecture/index.html"
          target="_blank"
          rel="noopener noreferrer"
          style={{
            display: 'inline-flex', alignItems: 'center', gap: 8,
            fontSize: 12, fontWeight: 600, color: '#34d399',
            padding: '8px 14px', border: '1px solid #2a2d3e', borderRadius: 8,
            background: 'rgba(52,211,153,0.06)', textDecoration: 'none',
          }}
        >
          🏗 View the Studio's own architecture (v2.0) ↗
        </a>
      </div>

      {/* Build info */}
      <div style={{ borderTop: '1px solid var(--border)', paddingTop: 16, display: 'flex', flexDirection: 'column', gap: 4 }}>
        {[
          ['Version',    '1.0.0'],
          ['Created by', 'Ravi Natarajan & Claude Code'],
          ['Framework',  'K9-AIF · Architecture-First Agentic AI'],
          ['Website',    'k9x.ai'],
        ].map(([label, value]) => (
          <div key={label as string} style={{ display: 'flex', gap: 12, fontSize: 11 }}>
            <span style={{ color: '#475569', minWidth: 90 }}>{label as string}</span>
            {label === 'Website'
              ? <a href="https://k9x.ai" target="_blank" rel="noopener noreferrer" style={{ color: '#6366f1' }}>{value as string}</a>
              : <span style={{ color: '#64748b' }}>{value as string}</span>
            }
          </div>
        ))}
      </div>
    </div>
  )
}
