import { useMemo, useState, useRef, useCallback, useEffect } from 'react';
import type { Node, Edge } from '@xyflow/react';
import { useStore } from '../store';
import type { NodeData, ProjectMeta } from '../types';

type Tab = 'log' | 'config' | 'flows' | 'governance' | 'orchestrators' | 'squads';

function toSnake(s: string): string {
  return s.replace(/([a-z])([A-Z])/g, '$1_$2').replace(/[\s-]+/g, '_').toLowerCase();
}

const PLATFORM_NOTES: Record<string, string> = {
  'watsonx-assistant':   'IBM watsonx Assistant — conversational AI layer for user-facing interactions',
  'watsonx-orchestrate': 'IBM watsonx Orchestrate — enterprise orchestration; maps to K9-AIF Orchestrator tier',
  'watsonx-governance':  'IBM watsonx Governance — AI Factsheets + model risk management; attach to ModelRouter',
  'watsonx-data':        'IBM watsonx.data — governed data lakehouse; use as retrieval/RAG data source',
  'crewai':              'CrewAI — agent execution via k9_aif.adapters.crewai.CrewAIAgentAdapter',
  'langchain':           'LangChain — chain/tool integration via k9_aif.adapters.langchain.LangChainAdapter',
};

function genConfig(project: ProjectMeta): string {
  const lines: string[] = [];
  lines.push(`# K9-AIF Configuration — ${project.project_name}`);
  lines.push(`# Generated by k9x_studio`);
  lines.push('');
  lines.push('app:');
  lines.push(`  name: "${project.project_name}"`);
  lines.push(`  author: "${project.author}"`);
  lines.push(`  domain: "${project.domain}"`);
  lines.push('');

  if (project.platforms && project.platforms.length > 0) {
    const watsonx = project.platforms.filter((p) => p.startsWith('watsonx-'));
    const frameworks = project.platforms.filter((p) => !p.startsWith('watsonx-'));
    lines.push('platforms:');
    if (watsonx.length) {
      lines.push('  ibm_watsonx:');
      watsonx.forEach((p) => lines.push(`    - ${p.replace('watsonx-', '')}`));
    }
    if (frameworks.length) {
      lines.push('  agent_frameworks:');
      frameworks.forEach((p) => lines.push(`    - ${p}`));
    }
    lines.push('  notes:');
    project.platforms.forEach((p) => {
      if (PLATFORM_NOTES[p]) lines.push(`    - "${PLATFORM_NOTES[p]}"`);
    });
    lines.push('');
  }

  lines.push(`inference:
  llm_factory:
    backend: ollama
    provider: ollama
    base_url: "http://localhost:11434"
    models:
      general:
        model: "llama3.2:1b"
        temperature: 0.3
        max_tokens: 2048
      reasoning:
        model: "granite3-dense:2b"
        temperature: 0.2
        max_tokens: 4096

  router:
    type: k9_model_router
    default_model: general
    persistence:
      enabled: true
      provider: sqlite

  model_catalog:
    default_model: general
    models:
      general:
        provider: ollama
        llm_ref: general
        capabilities: [general, chat, summarization]
        latency_tier: realtime
        cost_tier: minimal
      reasoning:
        provider: ollama
        llm_ref: reasoning
        capabilities: [reasoning, analysis, extraction]
        latency_tier: interactive
        cost_tier: standard

monitoring:
  console: true
  log_level: INFO`);

  return lines.join('\n');
}

function genFlows(nodes: Node<NodeData>[], edges: Edge[]): string {
  const router = nodes.find((n) => n.data.componentType === 'router');
  const orchs  = nodes.filter((n) => n.data.componentType === 'orchestrator');
  const squads = nodes.filter((n) => n.data.componentType === 'squad');
  const agents = nodes.filter((n) =>
    ['agent', 'validation_loop', 'critic_actor', 'guard'].includes(n.data.componentType)
  );

  if (!router && !orchs.length) return '# Add nodes to the canvas to see the execution flow';

  const lines: string[] = ['# flows.yaml — K9-AIF Execution Flow', ''];
  lines.push(`flows:`);
  lines.push(`  entry_point: ${router?.data.label ?? 'K9EventRouter'}`);
  lines.push('');
  lines.push('  steps:');

  orchs.forEach((o) => {
    lines.push(`    - id: ${toSnake(o.data.label)}`);
    lines.push(`      type: orchestrator`);
    lines.push(`      class: ${o.data.label}`);
    const squadIds = edges.filter((e) => e.source === o.id).map((e) => e.target);
    const orchSquads = squads.filter((s) => squadIds.includes(s.id));
    orchSquads.forEach((sq) => {
      lines.push(`      squad: ${sq.data.label}`);
      const agentIds = edges.filter((e) => e.source === sq.id).map((e) => e.target);
      const sqAgents = agents.filter((a) => agentIds.includes(a.id));
      if (sqAgents.length) {
        lines.push('      agents:');
        sqAgents.forEach((a) => lines.push(`        - ${a.data.label}`));
      }
    });
    lines.push('');
  });

  return lines.join('\n');
}

function genGovernance(nodes: Node<NodeData>[]): string {
  const guards = nodes.filter((n) => n.data.componentType === 'guard');

  const lines: string[] = ['# governance.yaml — K9-AIF Zero-Trust Governance', ''];
  lines.push('governance:');
  lines.push('  enabled: ' + (guards.length > 0 ? 'true' : 'false'));
  lines.push('  mode: zero_trust');
  lines.push('');

  if (guards.length) {
    lines.push('  guards:');
    guards.forEach((g) => {
      lines.push(`    - id: ${toSnake(g.data.label)}`);
      lines.push(`      class: ${g.data.abbClass ?? 'BaseGovernance'}`);
      lines.push(`      description: "${g.data.description || 'Governance guard'}"`);
      lines.push('      policy:');
      lines.push('        allow_by_default: false');
      lines.push('        audit_log: true');
      lines.push('');
    });
  } else {
    lines.push('  # No Guard nodes on canvas — add a Guard to enable zero-trust policies');
    lines.push('');
    lines.push('  # Example policy:');
    lines.push('  # guards:');
    lines.push('  #   - id: default_guard');
    lines.push('  #     class: BaseGovernance');
    lines.push('  #     policy:');
    lines.push('  #       allow_by_default: false');
    lines.push('  #       audit_log: true');
  }

  lines.push('audit:');
  lines.push('  enabled: true');
  lines.push('  sink: console');

  return lines.join('\n');
}

function genOrchestrators(nodes: Node<NodeData>[], edges: Edge[]): string {
  const orchs  = nodes.filter((n) => n.data.componentType === 'orchestrator');
  const squads = nodes.filter((n) => n.data.componentType === 'squad');
  const router = nodes.find((n) => n.data.componentType === 'router');
  if (!orchs.length) return '# No orchestrators defined yet — add Orchestrator nodes to the canvas';

  const lines: string[] = ['# orchestrators.yaml — K9-AIF Orchestrator Definitions', ''];
  lines.push('router:');
  lines.push(`  class: ${router?.data.label ?? 'K9EventRouter'}`);
  lines.push('  routes:');
  orchs.forEach((o) => {
    const domain = toSnake(o.data.label.replace(/orchestrator/i, '').trim()) || 'default';
    lines.push(`    ${domain}: ${o.data.label}`);
  });
  lines.push('');

  lines.push('orchestrators:');
  orchs.forEach((o) => {
    const squadIds = edges.filter((e) => e.source === o.id).map((e) => e.target);
    const sq = squads.find((s) => squadIds.includes(s.id));
    lines.push(`  ${toSnake(o.data.label)}:`);
    lines.push(`    class: ${o.data.label}`);
    lines.push(`    base: BaseOrchestrator`);
    lines.push(`    squad: ${sq?.data.label ?? '<SquadName>'}`);
    lines.push(`    retry_policy: ${(o.data as any).retryPolicy ?? 'none'}`);
    lines.push('');
  });

  return lines.join('\n');
}

function genSquads(nodes: Node<NodeData>[], edges: Edge[]): string {
  const squads = nodes.filter((n) => n.data.componentType === 'squad');
  const agents = nodes.filter((n) =>
    ['agent', 'validation_loop', 'critic_actor', 'guard'].includes(n.data.componentType)
  );
  if (!squads.length) return '# No squads defined yet — add Squad nodes to the canvas';

  const lines: string[] = ['# squads.yaml — K9-AIF Squad Definitions', '', 'squads:'];
  squads.forEach((sq) => {
    const agentIds = edges.filter((e) => e.source === sq.id).map((e) => e.target);
    const sqAgents = agents.filter((a) => agentIds.includes(a.id));
    lines.push(`  ${toSnake(sq.data.label)}:`);
    lines.push(`    label: "${sq.data.label}"`);
    lines.push(`    description: "${sq.data.description || sq.data.label + ' agent pipeline'}"`);
    lines.push('    agents:');
    sqAgents.forEach((a) => lines.push(`      - ${a.data.label}`));
    lines.push('    flow:');
    sqAgents.forEach((a) => {
      lines.push(`      - agent: ${a.data.label}`);
      lines.push(`        result_key: ${toSnake(a.data.label)}`);
    });
    lines.push('');
  });
  return lines.join('\n');
}

const TAB_LABELS: { id: Tab; label: string }[] = [
  { id: 'config',        label: 'config.yaml' },
  { id: 'flows',         label: 'flows.yaml' },
  { id: 'governance',    label: 'governance.yaml' },
  { id: 'orchestrators', label: 'orchestrators.yaml' },
  { id: 'squads',        label: 'squads.yaml' },
];

const MIN_HEIGHT = 160;
const MAX_HEIGHT = 320;
const DEFAULT_HEIGHT = 200;

const LEVEL_COLOR: Record<string, string> = { info: '#e2e8f0', warn: '#fbbf24', error: '#f87171' };

export function BottomPanel() {
  const [activeTab, setActiveTab] = useState<Tab>('config');
  const [height, setHeight] = useState(DEFAULT_HEIGHT);
  const isDragging = useRef(false);
  const logBottomRef = useRef<HTMLDivElement>(null);
  const { project, nodes, edges, logs } = useStore();

  useEffect(() => {
    logBottomRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [logs]);

  const n = nodes as Node<NodeData>[];

  const content = useMemo(() => {
    switch (activeTab) {
      case 'config':        return genConfig(project);
      case 'flows':         return genFlows(n, edges);
      case 'governance':    return genGovernance(n);
      case 'orchestrators': return genOrchestrators(n, edges);
      case 'squads':        return genSquads(n, edges);
    }
  }, [activeTab, project, nodes, edges]);

  const startResize = useCallback((e: React.MouseEvent) => {
    e.preventDefault();
    isDragging.current = true;
    const startY = e.clientY;
    const startH = height;
    const onMove = (ev: MouseEvent) =>
      setHeight(Math.max(MIN_HEIGHT, Math.min(MAX_HEIGHT, startH - (ev.clientY - startY))));
    const onUp = () => {
      isDragging.current = false;
      document.removeEventListener('mousemove', onMove);
      document.removeEventListener('mouseup', onUp);
    };
    document.addEventListener('mousemove', onMove);
    document.addEventListener('mouseup', onUp);
  }, [height]);

  return (
    <div className="bottom-panel" style={{ height, maxHeight: 'calc(40vh)' }}>
      <div className="bottom-resizer" onMouseDown={startResize} title="Drag to resize" />
      <div className="bottom-tabs">
        {TAB_LABELS.map((t) => (
          <button
            key={t.id}
            className={`bottom-tab ${activeTab === t.id ? 'active' : ''}`}
            onClick={() => setActiveTab(t.id)}
          >
            {t.label}
          </button>
        ))}
        <div className="bottom-tabs-spacer" />
        <button
          className={`bottom-tab ${activeTab === 'log' ? 'active' : ''}`}
          onClick={() => setActiveTab('log')}
          style={{ color: activeTab === 'log' ? '#58a6ff' : '#4a7ab5', borderColor: activeTab === 'log' ? '#58a6ff' : 'transparent' }}
        >
          ⬡ Activity Log {logs.length > 0 && <span style={{ fontSize: 9, marginLeft: 4, color: '#484f58' }}>{logs.length}</span>}
        </button>
        <button onClick={() => setHeight(DEFAULT_HEIGHT)} title="Reset height" style={{ background: 'none', border: 'none', color: '#484f58', cursor: 'pointer', fontSize: 12, padding: '0 6px' }}>⊟</button>
      </div>
      {activeTab === 'log' ? (
        <div style={{
          flex: 1, display: 'flex', flexDirection: 'column',
          background: '#0d1117', fontFamily: "'SF Mono', 'Fira Code', monospace",
        }}>
          <div style={{
            display: 'flex', alignItems: 'center', gap: 16,
            background: '#161b22', borderBottom: '1px solid #21262d',
            padding: '0 12px', height: 26, flexShrink: 0,
          }}>
            <span style={{ fontSize: 11, color: '#58a6ff', fontWeight: 600, letterSpacing: '0.5px' }}>ACTIVITY LOG</span>
            <span style={{ fontSize: 10, color: '#484f58' }}>{logs.length} entries</span>
          </div>
          <div style={{ flex: 1, overflowY: 'auto', padding: '6px 16px', scrollbarWidth: 'thin', scrollbarColor: '#2a2d3e #0d1117' }}>
            {logs.length === 0
              ? <div style={{ fontSize: 12, color: '#6e7681', marginTop: 8, fontStyle: 'italic' }}>— waiting for activity —</div>
              : logs.map((l) => (
                <div key={l.id} style={{ fontSize: 12.5, lineHeight: '22px', color: LEVEL_COLOR[l.level] ?? '#e2e8f0', display: 'flex', gap: 10 }}>
                  <span style={{ color: '#484f58', flexShrink: 0 }}>{l.ts}</span>
                  <span>{l.msg}</span>
                </div>
              ))
            }
            <div ref={logBottomRef} />
          </div>
        </div>
      ) : (
        <pre className="bottom-content">{content}</pre>
      )}
    </div>
  );
}
