import { useState } from 'react';
import { useStore } from '../store';

function Section({ title, defaultOpen = false, children }: { title: string; defaultOpen?: boolean; children: React.ReactNode }) {
  const [open, setOpen] = useState(defaultOpen);
  return (
    <div style={{ marginBottom: 12 }}>
      <button onClick={() => setOpen(v => !v)} style={{
        width: '100%', display: 'flex', alignItems: 'center', justifyContent: 'space-between',
        background: 'rgba(99,102,241,0.05)', border: '1px solid var(--border)',
        borderRadius: 6, padding: '7px 12px', cursor: 'pointer', marginBottom: open ? 10 : 0,
      }}>
        <span style={{ fontSize: 11, fontWeight: 600, color: '#8892a4', letterSpacing: '0.8px', textTransform: 'uppercase' }}>{title}</span>
        <span style={{ fontSize: 10, color: '#475569' }}>{open ? '▲' : '▼'}</span>
      </button>
      {open && <div>{children}</div>}
    </div>
  );
}

export function IntakePanel({ onSwitchTab }: { onSwitchTab?: (tab: string) => void }) {
  const { project, setProject, nodes, generating, setGenerating, llmConfig, addLog, setLlmActive, addGeneratedDoc, setPendingCanvasSuggestion, specImported, setSpecImported, clearCanvas, setLastSpecFile, setGenResult } = useStore();
  const [wifBusy, setWifBusy] = useState(false);
  const [specBusy, setSpecBusy] = useState(false);
  const [specError, setSpecError] = useState('');
  const [specFileName, setSpecFileName] = useState('');

  const set = (key: string, value: string) =>
    setProject({ ...project, [key]: value });

  const wifFilename = () => {
    const slugify = (s: string) => s.toLowerCase().trim().replace(/[^a-z0-9]+/g, '_').replace(/^_|_$/g, '');
    const proj = slugify(project.project_name || 'project');
    const app  = slugify((project as any).app_name || '');
    return app ? `${proj}_${app}_intake.md` : `${proj}_intake.md`;
  };

  const buildWIFContent = () => {
    const today = new Date().toISOString().split('T')[0];
    const s = (label: string, val: string) => val.trim() ? `\n## ${label}\n\n${val.trim()}\n` : '';
    return `# Work Intake Form — ${project.project_name || 'Untitled'}

**Date:** ${today}
**Author:** ${project.author || '—'}
**Application:** ${(project as any).app_name || '—'}
**Domain:** ${project.domain || '—'}
**Description:** ${project.description || '—'}
${s('Business Vision', (project as any).vision ?? '')}${s('Current State', (project as any).current_state ?? '')}${s('Pain Points', (project as any).pain_points ?? '')}${s('Target Goals', (project as any).target_goals ?? '')}${s('Notes', (project as any).notes ?? '')}
---
*Generated by K9X Studio*`.trim();
  };

  const handleGenerateWIF = async () => {
    setWifBusy(true);
    addLog(`Generating ${wifFilename()}…`);
    const content = buildWIFContent();

    addGeneratedDoc(wifFilename(), content);
    addLog('✓ initial_project_WIF.md generated — see Generated Docs tab');
    onSwitchTab?.('docs');

    if (project.project_folder) {
      try {
        const res = await fetch('/api/save-wif', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            project_folder: project.project_folder,
            project_name: project.project_name,
            author: project.author,
            domain: project.domain,
            description: project.description,
            vision: (project as any).vision ?? '',
            current_state: (project as any).current_state ?? '',
            target_goals: (project as any).target_goals ?? '',
            notes: (project as any).notes ?? '',
          }),
        });
        const data = await res.json();
        if (res.ok) addLog(`✓ Saved to disk → ${data.path}`);
      } catch { /* disk save optional */ }
    }
    setWifBusy(false);
  };


  return (
    <div className="intake-panel">
      <div className="intake-header">
        <div className="intake-title">Project Intake</div>
        <div className="intake-sub">Define your business context — the foundation for architecture generation</div>
        <button
          className="intake-clear-btn"
          onClick={() => {
            setProject({ project_name: '', app_name: '', author: '', domain: '', description: '', project_folder: '', framework_path: '', platforms: [] });
            setSpecImported(false);
            clearCanvas();
            addLog('Intake cleared — ready for new project');
          }}
          title="Clear all fields and start over"
        >✕ Clear</button>
      </div>

      <div className="intake-form">

        {/* Seed options — top */}
        <div className="intake-seed-row">
          <label className={`intake-bpmn-btn${specBusy ? ' intake-bpmn-btn--busy' : ''}`} title="Upload a .md document — extracts project info and auto-generates canvas (.docx and .pdf support coming soon)">
            <span>{specBusy ? '⟳ Processing…' : '⬆ Upload Spec Doc'}</span>
            <input
              type="file"
              accept=".md,.txt"
              style={{ display: 'none' }}
              disabled={specBusy}
              onChange={async (e) => {
                const file = e.target.files?.[0];
                e.target.value = '';
                if (!file) return;
                setSpecBusy(true); setSpecError(''); setGenerating(true);
                onSwitchTab?.('canvas');
                addLog(`Importing spec doc: ${file.name}…`);
                const fd = new FormData();
                fd.append('file', file);
                if (llmConfig?.endpoint?.trim()) {
                  fd.append('llm_config', JSON.stringify(llmConfig));
                  addLog(`Spec import — using LLM (${llmConfig.endpoint})…`);
                  setLlmActive(true);
                } else {
                  addLog('Spec import — rule-based (no LLM configured)');
                }
                try {
                  const res = await fetch('/api/spec/import', { method: 'POST', body: fd });
                  const data = await res.json();
                  if (!res.ok) throw new Error(data.detail ?? `Server error ${res.status}`);
                  if (data.intake) {
                    setProject({ ...project, ...data.intake });
                  }
                  if (data.suggestion) {
                    setPendingCanvasSuggestion(data.suggestion);
                    onSwitchTab?.('canvas');
                  }
                  setSpecImported(true);
                  setSpecFileName(file.name);
                  setLastSpecFile(file);
                  const sc = data.scoring;
                  if (sc) {
                    const w = sc[sc.winner];
                    const l = sc.winner === 'llm' ? sc.rule_based : sc.llm;
                    const wLabel = sc.winner === 'llm' ? 'LLM' : 'Rule-based';
                    const lLabel = sc.winner === 'llm' ? 'Rule-based' : 'LLM';
                    setGenResult({ winner: wLabel, winnerScore: w?.score, winnerAgents: w?.agent_count, winnerSquads: w?.squad_count });
                    addLog(`✓ ${wLabel} selected (score: ${w?.score}) — ${w?.agent_count} agents, ${w?.squad_count} squads`);
                    addLog(`  ${lLabel} score: ${l?.score} (${l?.agent_count} agents) — not selected`);
                  } else {
                    addLog(`✓ Spec imported · ${(data.suggestion?.agents ?? []).length} agents`);
                  }
                } catch (err: any) {
                  setSpecError(`Failed — ${err.message ?? 'unknown'}`);
                  addLog(`Spec import failed: ${err.message ?? 'unknown'}`, 'error');
                } finally {
                  setLlmActive(false);
                  setGenerating(false);
                  setSpecBusy(false);
                }
              }}
            />
          </label>
          <label className="intake-bpmn-btn" title="IBM Blueworks Live · Camunda · Bizagi (.bpmn, .xml, .zip)">
            <span>⬆ Upload BPMN</span>
            <input
              type="file"
              accept=".bpmn,.xml,.zip"
              style={{ display: 'none' }}
              onChange={async (e) => {
                const file = e.target.files?.[0];
                e.target.value = '';
                if (!file) return;
                setPendingCanvasSuggestion(null);
                clearCanvas();
                setGenerating(true);
                onSwitchTab?.('canvas');
                await new Promise(r => setTimeout(r, 50)); // let overlay render
                const fd = new FormData();
                fd.append('file', file);
                if (llmConfig?.endpoint?.trim()) {
                  fd.append('llm_config', JSON.stringify(llmConfig));
                  addLog(`BPMN import — using LLM (${llmConfig.endpoint})…`);
                  setLlmActive(true);
                } else {
                  addLog(`BPMN import — rule-based (${file.name})…`);
                }
                try {
                  const res = await fetch('/api/bpmn/import', { method: 'POST', body: fd });
                  const data = await res.json();
                  if (!res.ok) throw new Error(data.detail ?? `Server error ${res.status}`);
                  if (data.process_name) setProject({ ...project, project_name: data.process_name });
                  if (data.suggestion) {
                    setPendingCanvasSuggestion(data.suggestion);
                    onSwitchTab?.('canvas');
                  }
                  addLog(`BPMN imported · source: ${data.source ?? 'bpmn'} · ${(data.suggestion?.agents ?? []).length} agents`);
                } catch (err: any) {
                  addLog(`BPMN import failed: ${err.message ?? 'unknown'}`, 'error');
                } finally {
                  setLlmActive(false);
                  setGenerating(false);
                }
              }}
            />
          </label>
          {specBusy && (
            <div style={{ fontSize: 11, color: '#f59e0b', marginTop: 4, display: 'flex', alignItems: 'center', gap: 6 }}>
              <span style={{ animation: 'spin 1s linear infinite', display: 'inline-block' }}>⟳</span>
              Processing document — LLM analysing, please wait…
            </div>
          )}
          {specFileName && !specError && (
            <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginTop: 4, flexWrap: 'wrap' }}>
              <div style={{
                fontSize: 11, color: '#34d399',
                background: 'rgba(52,211,153,0.08)', border: '1px solid rgba(52,211,153,0.25)',
                borderRadius: 4, padding: '3px 8px',
              }}>
                ✓ {specFileName}
              </div>
            </div>
          )}
          {specError && (
            <div style={{ fontSize: 11, color: '#f87171', marginTop: 4 }}>
              ✕ {specError} — check Activity Log
            </div>
          )}
        </div>

        {/* ── Section 1: Basic Info ── */}
        <Section title="Basic Info" defaultOpen={true}>
          <div className="intake-field">
            <label className="intake-label">Industry Blueprint</label>
            <select className="intake-input" disabled>
              <option value="">— select a blueprint (coming soon) —</option>
            </select>
          </div>
          <div className="intake-row-2">
            <div className="intake-field">
              <label className="intake-label">Project Name <span style={{ color: '#f87171', marginLeft: 2 }}>*</span></label>
              <input className="intake-input" placeholder="e.g. Insurance Transformation 2026" value={project.project_name} onChange={(e) => set('project_name', e.target.value)} />
            </div>
            <div className="intake-field">
              <label className="intake-label">Application Name</label>
              <input className="intake-input" placeholder="e.g. Enterprise Claims Processor" value={(project as any).app_name ?? ''} onChange={(e) => set('app_name', e.target.value)} />
            </div>
          </div>
          <div className="intake-row-2">
            <div className="intake-field">
              <label className="intake-label">Domain</label>
              <input className="intake-input" placeholder="e.g. Insurance / Banking / Healthcare" value={project.domain} onChange={(e) => set('domain', e.target.value)} />
            </div>
            <div className="intake-field">
              <label className="intake-label">Author</label>
              <input className="intake-input" placeholder="Your name" value={project.author} onChange={(e) => set('author', e.target.value)} />
            </div>
          </div>
          <div className="intake-field">
            <label className="intake-label">Description <span style={{ color: '#94a3b8', fontSize: 9, marginLeft: 2 }}>* at least one context field required</span></label>
            <textarea className="intake-textarea" placeholder="Describe the application — what it does, who uses it, and the business context" value={project.description} onChange={(e) => set('description', e.target.value)} rows={3} />
          </div>
        </Section>

        {/* ── Section 2: Business Context ── */}
        <Section title="Business Context">
          <div className="intake-field">
            <label className="intake-label">Business Vision</label>
            <textarea className="intake-textarea" placeholder="What is the desired end-state? What business problem does this solve?" value={(project as any).vision ?? ''} onChange={(e) => set('vision', e.target.value)} rows={3} />
          </div>
          <div className="intake-field">
            <label className="intake-label">Current State</label>
            <textarea className="intake-textarea" placeholder="Describe the current process, pain points, and limitations" value={(project as any).current_state ?? ''} onChange={(e) => set('current_state', e.target.value)} rows={3} />
          </div>
          <div className="intake-field">
            <label className="intake-label">Pain Points</label>
            <textarea className="intake-textarea" placeholder="Key pain points, blockers, and frustrations with the current state" value={(project as any).pain_points ?? ''} onChange={(e) => set('pain_points', e.target.value)} rows={2} />
          </div>
          <div className="intake-field">
            <label className="intake-label">Target Goals</label>
            <textarea className="intake-textarea" placeholder="Key objectives, KPIs, and success metrics" value={(project as any).target_goals ?? ''} onChange={(e) => set('target_goals', e.target.value)} rows={3} />
          </div>
          <div className="intake-field">
            <label className="intake-label">Notes</label>
            <textarea className="intake-textarea" placeholder="Additional context, stakeholders, constraints, preferred models…" value={(project as any).notes ?? ''} onChange={(e) => set('notes', e.target.value)} rows={2} />
          </div>
        </Section>

        {/* ── Section 3: Key Processes (enriches LLM) ── */}
        <Section title="Key Processes — optional, enriches LLM generation">
          <div className="intake-field">
            <label className="intake-label">Main Workflows</label>
            <textarea className="intake-textarea" placeholder="List 3-5 main business workflows (one per line)&#10;e.g. Claim Intake&#10;Fraud Detection&#10;Payment Processing" value={(project as any).key_processes ?? ''} onChange={(e) => set('key_processes', e.target.value)} rows={4} />
          </div>
          <div className="intake-field">
            <label className="intake-label">Volume & SLA</label>
            <input className="intake-input" placeholder="e.g. 1000 events/day, response < 2s" value={(project as any).volume_sla ?? ''} onChange={(e) => set('volume_sla', e.target.value)} />
          </div>
        </Section>

        {/* ── Section 4: Systems & Integration ── */}
        <Section title="Systems & Integration — optional, enriches LLM generation">
          <div className="intake-field">
            <label className="intake-label">Systems of Record</label>
            <textarea className="intake-textarea" placeholder="e.g. Salesforce CRM, SAP ERP, IBM FileNet, Oracle Financials" value={(project as any).systems_of_record ?? ''} onChange={(e) => set('systems_of_record', e.target.value)} rows={2} />
          </div>
          <div className="intake-field">
            <label className="intake-label">Integration Patterns</label>
            <input className="intake-input" placeholder="e.g. REST APIs, Apache Kafka, Batch, IBM MQ" value={(project as any).integration_patterns ?? ''} onChange={(e) => set('integration_patterns', e.target.value)} />
          </div>
        </Section>

        {/* ── Section 5: Governance ── */}
        <Section title="Governance & Compliance — optional, enriches LLM generation">
          <div className="intake-field">
            <label className="intake-label">Compliance Requirements</label>
            <input className="intake-input" placeholder="e.g. HIPAA, GDPR, SOX, PCI-DSS" value={(project as any).compliance_requirements ?? ''} onChange={(e) => set('compliance_requirements', e.target.value)} />
          </div>
          <div className="intake-field">
            <label className="intake-label">Human-in-the-Loop Decisions</label>
            <textarea className="intake-textarea" placeholder="Which decisions require human approval? e.g. Payments > $50K, Fraud escalations, Coverage denials" value={(project as any).hitl_decisions ?? ''} onChange={(e) => set('hitl_decisions', e.target.value)} rows={2} />
          </div>
        </Section>


        <div className="intake-actions">
          {nodes.length === 0 && (
            <button
              className="intake-btn-flow"
              onClick={async () => {
                const hasContext = project.description.trim() || (project as any).vision?.trim() || (project as any).current_state?.trim() || (project as any).pain_points?.trim() || (project as any).target_goals?.trim();
                if (generating || !hasContext) return;
                setGenerating(true);
                const usingLlm = Boolean(llmConfig?.endpoint?.trim());
                addLog(usingLlm ? `Generating flow via LLM…` : 'Generating flow (rule-based)…');
                if (usingLlm) setLlmActive(true);
                try {
                  const payload: any = { ...project };
                  if (usingLlm) payload.llm = llmConfig;
                  const res = await fetch('/api/suggest', {
                    method: 'POST', headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify(payload),
                  });
                  const data = await res.json();
                  if (data.suggestion) {
                    setPendingCanvasSuggestion(data.suggestion);
                    onSwitchTab?.('canvas');
                    addLog(`Flow generated · source: ${data.source ?? 'default'}`);
                  }
                } catch (err: any) {
                  addLog(`Flow generation failed: ${err.message ?? 'unknown'}`, 'error');
                } finally {
                  setGenerating(false);
                  setLlmActive(false);
                }
              }}
              disabled={generating || !project.project_name.trim() || (!project.description.trim() && !(project as any).vision?.trim() && !(project as any).current_state?.trim() && !(project as any).pain_points?.trim() && !(project as any).target_goals?.trim())}
              title="Generate architecture flow on canvas"
            >
              {generating ? '⟳ Generating…' : '✦ Generate Flow'}
            </button>
          )}
          <button
            className="intake-btn-generate"
            onClick={handleGenerateWIF}
            disabled={wifBusy || !project.project_name.trim() || specImported}
            title={specImported ? 'Spec document already uploaded — WIF not needed' : !project.project_name.trim() ? 'Enter a project name first' : 'Generate Work Intake Form'}
          >
            {wifBusy ? '⟳ Generating…' : `Generate ${wifFilename()}`}
          </button>
        </div>

      </div>
    </div>
  );
}
