// PlantUML class diagram generation — mirrors
// backend/services/scaffold_service.py::generate_class_diagram_puml so the
// live "Class Diagram" tab matches what gets written into the scaffold ZIP.

export interface ClassDiagramAgent {
  name: string;
  type?: string;
}

export interface ClassDiagramSquad {
  name: string;
  agents: string[];
}

export interface ClassDiagramOrchestrator {
  name: string;
  squad?: string;
}

export interface ClassDiagramProject {
  project_name: string;
  agents: ClassDiagramAgent[];
  squads: ClassDiagramSquad[];
  orchestrators: ClassDiagramOrchestrator[];
}

const KNOWN_AGENT_BASE_TYPES = ['BaseAgent', 'K9ValidationLoopAgent', 'K9CriticActorAgent'];

export function toSnake(name: string): string {
  return name
    .replace(/[\s-]+/g, '_')
    .replace(/([a-z0-9])([A-Z])/g, '$1_$2')
    .replace(/_+/g, '_')
    .toLowerCase()
    .replace(/^_|_$/g, '');
}

export function toPascal(name: string): string {
  return toSnake(name)
    .split('_')
    .filter(Boolean)
    .map((p) => p.charAt(0).toUpperCase() + p.slice(1))
    .join('');
}

function agentBase(agent: ClassDiagramAgent): string {
  const t = agent.type ?? 'BaseAgent';
  return KNOWN_AGENT_BASE_TYPES.includes(t) ? t : 'BaseAgent';
}

/**
 * Build the PlantUML source for a project's class diagram — agents, squads
 * and orchestrators plus the K9-AIF ABB/OOB base classes they extend.
 * Follows the conventions in puml/README.md (abstract vs concrete marking,
 * package-per-squad grouping, `--|>` inheritance, `..>` "loads" dependency).
 */
export function buildClassDiagramPuml(project: ClassDiagramProject): string {
  const appName = toPascal(project.project_name || 'Project');
  const appFolder = toSnake(project.project_name || 'project');

  const agents = project.agents ?? [];
  const squads = project.squads ?? [];
  const orchestrators = project.orchestrators ?? [];

  const usedTypes = new Set(agents.map(agentBase));
  const hasValidation = usedTypes.has('K9ValidationLoopAgent');
  const hasCritic = usedTypes.has('K9CriticActorAgent');

  const lines: string[] = [];
  lines.push(`@startuml ${appFolder}_class_diagram`);
  lines.push('');
  lines.push("' Generated by k9x Studio. k9x.ai");
  lines.push('');
  lines.push('skinparam classBackgroundColor #FAFAFA');
  lines.push('skinparam classBorderColor #AAAAAA');
  lines.push('skinparam ArrowColor #555555');
  lines.push('skinparam PackageBorderColor #CCCCCC');
  lines.push('skinparam PackageBackgroundColor #F5F7FF');
  lines.push('skinparam defaultFontSize 12');
  lines.push('hide circle');
  lines.push('');
  lines.push(`title ${appName} - Class Diagram`);
  lines.push('');

  // ── K9-AIF framework base classes (ABB / OOB) ───────────────────────
  lines.push('package "K9-AIF Framework (ABB / OOB)" #E8F5E9 {');
  lines.push('  abstract class BaseAgent {');
  lines.push('    + {abstract} execute(payload: dict) : dict');
  lines.push('  }');

  if (hasValidation) {
    lines.push('  abstract class BaseValidationLoopAgent {');
    lines.push('    + execute(payload: dict) : dict');
    lines.push('    + {abstract} generate_hypothesis(loop_ctx)');
    lines.push('    + {abstract} run_validation(hypothesis, loop_ctx)');
    lines.push('    + {abstract} evaluate_observation(result, loop_ctx)');
    lines.push('    + {abstract} should_continue(obs, loop_ctx) : ValidationDisposition');
    lines.push('    + {abstract} finalize(loop_ctx) : ValidationLoopResult');
    lines.push('  }');
    lines.push('  class K9ValidationLoopAgent');
    lines.push('  BaseAgent <|-- BaseValidationLoopAgent');
    lines.push('  BaseValidationLoopAgent <|-- K9ValidationLoopAgent');
  }

  if (hasCritic) {
    lines.push('  abstract class BaseCriticActorAgent {');
    lines.push('    + execute(payload: dict) : dict');
    lines.push('    + {abstract} generate(ctx)');
    lines.push('    + {abstract} critique(draft, ctx) : dict');
    lines.push('    + {abstract} refine(draft, feedback, ctx)');
    lines.push('    + {abstract} should_accept(critique, ctx) : bool');
    lines.push('    + {abstract} finalize(ctx) : CriticActorResult');
    lines.push('  }');
    lines.push('  class K9CriticActorAgent');
    lines.push('  BaseAgent <|-- BaseCriticActorAgent');
    lines.push('  BaseCriticActorAgent <|-- K9CriticActorAgent');
  }

  if (squads.length > 0) {
    lines.push('  class BaseSquad {');
    lines.push('    + execute(payload: dict) : dict');
    lines.push('  }');
  }

  if (orchestrators.length > 0) {
    lines.push('  abstract class BaseOrchestrator {');
    lines.push('    + {abstract} execute_flow(payload: dict) : dict');
    lines.push('  }');
  }

  lines.push('}');
  lines.push('');

  // ── agents, grouped by squad ─────────────────────────────────────────
  if (agents.length > 0) {
    const squadAgentNames = new Set(squads.flatMap((sq) => sq.agents ?? []));
    const unassigned = agents.filter((a) => !squadAgentNames.has(a.name));

    lines.push(`package "${appName} Agents" {`);
    for (const sq of squads) {
      lines.push(`  package "${sq.name}" {`);
      for (const agentName of sq.agents ?? []) {
        lines.push(`    class ${agentName}`);
      }
      lines.push(`    class ${sq.name}`);
      lines.push('  }');
    }
    if (unassigned.length > 0) {
      if (squads.length > 0) {
        lines.push('  package "Unassigned" {');
        for (const a of unassigned) {
          lines.push(`    class ${a.name}`);
        }
        lines.push('  }');
      } else {
        for (const a of unassigned) {
          lines.push(`  class ${a.name}`);
        }
      }
    }
    lines.push('}');
    lines.push('');

    // agent → base class
    for (const a of agents) {
      lines.push(`${agentBase(a)} <|-- ${a.name}`);
    }
    lines.push('');

    // squad → BaseSquad, squad *-- agents
    for (const sq of squads) {
      lines.push(`BaseSquad <|-- ${sq.name}`);
      for (const agentName of sq.agents ?? []) {
        lines.push(`${sq.name} *-- ${agentName}`);
      }
    }
    if (squads.length > 0) lines.push('');
  }

  // ── orchestrators ────────────────────────────────────────────────────
  if (orchestrators.length > 0) {
    lines.push(`package "${appName} Orchestrators" {`);
    for (const o of orchestrators) {
      lines.push(`  class ${o.name}`);
    }
    lines.push('}');
    lines.push('');
    for (const o of orchestrators) {
      lines.push(`BaseOrchestrator <|-- ${o.name}`);
      if (o.squad) {
        lines.push(`${o.name} ..> ${o.squad} : loads`);
      }
    }
    lines.push('');
  }

  // ── legend: what the arrows/lines mean ──────────────────────────────
  lines.push('legend bottom right');
  lines.push('|= Notation |= Meaning |');
  lines.push('| ──▷ | Inheritance (extends) |');
  lines.push('| ──◆ | Composition (owns) |');
  lines.push('| ╌╌> | Dependency (uses) |');
  lines.push('endlegend');
  lines.push('');

  lines.push('@enduml');
  return lines.join('\n');
}

const PLANTUML_SERVER = 'https://www.plantuml.com/plantuml';

/** UTF-8 bytes of the PlantUML source as a lowercase hex string — the `~h` raw-hex encoding the PlantUML server accepts with no zlib/deflate step. Roughly doubles the source size, so it's only used as a fallback for small diagrams when deflate compression isn't available. */
function plantUmlHex(puml: string): string {
  const bytes = new TextEncoder().encode(puml);
  return Array.from(bytes)
    .map((b) => b.toString(16).padStart(2, '0'))
    .join('');
}

const PLANTUML_ALPHABET = '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz-_';

function encode6bit(b: number): string {
  return PLANTUML_ALPHABET[b & 0x3f];
}

function append3bytes(b1: number, b2: number, b3: number): string {
  return (
    encode6bit(b1 >> 2) +
    encode6bit(((b1 & 0x3) << 4) | (b2 >> 4)) +
    encode6bit(((b2 & 0xf) << 2) | (b3 >> 6)) +
    encode6bit(b3 & 0x3f)
  );
}

/** PlantUML's "deflate + custom base64" encoding via the browser's native Compression Streams API (no extra deps) — much more compact than `~h<hex>`, needed for diagrams of non-trivial projects whose hex-encoded URL would exceed the server's GET length limit. */
async function plantUmlDeflateEncode(puml: string): Promise<string> {
  const stream = new Blob([puml]).stream().pipeThrough(new CompressionStream('deflate-raw'));
  const buf = new Uint8Array(await new Response(stream).arrayBuffer());
  let out = '';
  for (let i = 0; i < buf.length; i += 3) {
    out += append3bytes(buf[i], buf[i + 1] ?? 0, buf[i + 2] ?? 0);
  }
  return out;
}

/** Build a PlantUML render URL for the given source, preferring the compact deflate encoding and falling back to `~h<hex>` if Compression Streams aren't available. */
export async function plantUmlRenderUrl(puml: string, format: 'svg' | 'png'): Promise<string> {
  try {
    const encoded = await plantUmlDeflateEncode(puml);
    return `${PLANTUML_SERVER}/${format}/${encoded}`;
  } catch {
    return `${PLANTUML_SERVER}/${format}/~h${plantUmlHex(puml)}`;
  }
}

export function plantUmlSvgUrl(puml: string): Promise<string> {
  return plantUmlRenderUrl(puml, 'svg');
}
