# SPDX-License-Identifier: Apache-2.0
"""Content written by `k9x config` — a starter .env for the K9-AIF Studio."""

ENV_EXAMPLE_CONTENT = """\
# k9x studio — local configuration
# ─────────────────────────────────────────────────────────────
# Copy of the settings k9x studio reads from the environment.
# Generated by `k9x config`. Edit the values below, then run:
#
#   k9x studio
#
# Uncomment exactly ONE provider block under "LLM Backend". The
# values shown are examples — replace endpoints, models and keys
# with your own. Never commit a real .env to source control.
# ─────────────────────────────────────────────────────────────

# ── LLM Backend ─────────────────────────────────────────────────
# Supported LLM_PROVIDER values: ollama | openai | anthropic | watsonx | custom
# Use an IP address or hostname — localhost is blocked on hosted instances
# (see K9X_BLOCK_LOCAL below).

# Ollama (default — local models, no API key required)
LLM_PROVIDER=ollama
LLM_ENDPOINT=http://127.0.0.1:11434
LLM_MODEL=granite3-dense:2b
LLM_API_KEY=

# OpenAI
# LLM_PROVIDER=openai
# LLM_ENDPOINT=https://api.openai.com/v1
# LLM_MODEL=gpt-4o-mini
# LLM_API_KEY=sk-...

# Anthropic / Claude
# LLM_PROVIDER=anthropic
# LLM_ENDPOINT=https://api.anthropic.com
# LLM_MODEL=claude-haiku-4-5-20251001
# LLM_API_KEY=sk-ant-...

# Grok / xAI (OpenAI-compatible — use the "custom" provider)
# LLM_PROVIDER=custom
# LLM_ENDPOINT=https://api.x.ai/v1
# LLM_MODEL=grok-2-latest
# LLM_API_KEY=xai-...

# IBM watsonx.ai (deployment inference endpoint)
# LLM_PROVIDER=watsonx
# LLM_ENDPOINT=https://us-south.ml.cloud.ibm.com/ml/v1/deployments/<deployment-id>
# LLM_MODEL=<deployment-id-or-model-name>
# LLM_API_KEY=<IAM bearer token>

# ── Governance LLM (internal — not user-facing) ───────────────
# Used only for document safety screening on upload.
# Separate from the user-configured LLM above. Granite Guardian recommended.
# Documents larger than GOVERNANCE_MAX_CHARS skip the LLM check (Layer 1 only).
GOVERNANCE_LLM_ENDPOINT=http://127.0.0.1:11434
GOVERNANCE_LLM_MODEL=granite3-guardian:latest
GOVERNANCE_MAX_CHARS=50000

# ── Studio runtime ─────────────────────────────────────────────
# Folder where generated projects are written/listed.
# Defaults to the current directory if unset.
# K9X_PROJECTS_ROOT=./k9x_projects

# Splash-screen login. Defaults to demo/demo if unset — set these to
# restrict access to your studio.
# K9X_STUDIO_USER=demo
# K9X_STUDIO_PASSWORD=demo

# Generator templates used when exporting a scaffold. k9x studio sets this
# automatically to its bundled copy — override only if you have a local
# k9-aif-framework checkout with newer templates.
# K9X_GENERATOR_TEMPLATES_DIR=/path/to/k9-aif-framework/generator/templates

# Set to 'true' only on public-hosted instances to block localhost LLM endpoints
K9X_BLOCK_LOCAL=false

# ── Future: additional external integrations ───────────────────
# Database passwords, third-party tokens, etc. go here as the studio grows.
# Example:
# DATABASE_URL=postgresql://user:password@host:5432/db
# SLACK_WEBHOOK_URL=https://hooks.slack.com/...
"""
